; Using seed 941350
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float -1.1509597301483154e-08 ***
	.dword 	$c5bbbe87
	.byte 	$66,$80
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 2.9999999884904027 ***
	.dword 	$bffffff3
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.6147363264026355e-14 ***
	.dword 	$cfd44998
	.byte 	$54,$0
	.byte 	1     ; *** Load Float 6.944804 ***
	.dword 	$de3bd599
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3.204843929854633e-13 ***
	.dword 	$b46aab27
	.byte 	$57,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 322.06131200000004 ***
	.dword 	$a107d912
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 65985475102837.31 ***
	.dword 	$f00dc337
	.byte 	$ae,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -65985475102515.25 ***
	.dword 	$f00dc337
	.byte 	$ae,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.11359 ***
	.dword 	$c3a2877e
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -3.60330432158662e-15 ***
	.dword 	$81d29dc7
	.byte 	$51,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 4.640573263168335e-08 ***
	.dword 	$c74fa483
	.byte 	$68,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -107.442176 ***
	.dword 	$d6e264e4
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 891.2 ***
	.dword 	$decccccc
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -95752.46725120001 ***
	.dword 	$bb043bce
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 620.22 ***
	.dword 	$9b0e147a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 5.324435 ***
	.dword 	$aa61c582
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 116.48559894148393 ***
	.dword 	$e8f8a06c
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 901866091579265.0 ***
	.dword 	$cd0f8401
	.byte 	$b2,$0
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 901866091579263.0 ***
	.dword 	$cd0f8401
	.byte 	$b2,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -34.87 ***
	.dword 	$8b7ae147
	.byte 	$86,$80
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -34.87 ***
	.dword 	$8b7ae147
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.924802 ***
	.dword 	$ecbfd2e9
	.byte 	$80,$0
	.byte 	1     ; *** Load Float -51.18 ***
	.dword 	$ccb851eb
	.byte 	$86,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 52.104802 ***
	.dword 	$d06b5137
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 620.94 ***
	.dword 	$9b3c28f5
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 0.990296 ***
	.dword 	$fd8409e5
	.byte 	$80,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 621.930296 ***
	.dword 	$9b7b89f8
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 1.376434 ***
	.dword 	$b02efd43
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -794.9 ***
	.dword 	$c6b99999
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 9.497764 ***
	.dword 	$97f6d762
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -785.402236 ***
	.dword 	$c459be3c
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -5.006097257137299e-09 ***
	.dword 	$ac0218de
	.byte 	$65,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2732088826.5277443 ***
	.dword 	$a2d85dfa
	.byte 	$a0,$80
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 303565425.1697494 ***
	.dword 	$90c05389
	.byte 	$9d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 169.0 ***
	.dword 	$a9000000
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.684502 ***
	.dword 	$af3b85e8
	.byte 	$80,$80
	.byte 	1     ; *** Load Float -0.684502 ***
	.dword 	$af3b85e8
	.byte 	$80,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.018698 ***
	.dword 	$c0992c8c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 9.98609 ***
	.dword 	$9fc7064e
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.6027081670603809 ***
	.dword 	$9a4b151a
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -4.520319635048509e-12 ***
	.dword 	$9f0b6b6e
	.byte 	$5b,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -18.99999999999548 ***
	.dword 	$97ffffff
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.758796 ***
	.dword 	$8c240746
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.663605 ***
	.dword 	$9a9e2046
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 20775386556036.81 ***
	.dword 	$97292c49
	.byte 	$ad,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 166203092448294.47 ***
	.dword 	$97292c49
	.byte 	$b0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.955106073291971e-13 ***
	.dword 	$c3c4d22c
	.byte 	$58,$0
	.byte 	1     ; *** Load Float 1.134294 ***
	.dword 	$91308bb9
	.byte 	$81,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 6.131660815707367e-13 ***
	.dword 	$ac9745c8
	.byte 	$58,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.884278 ***
	.dword 	$9e2600b0
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -152.2 ***
	.dword 	$98333333
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0649426938239159 ***
	.dword 	$8500acd0
	.byte 	$7d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -46943129978408.01 ***
	.dword 	$aac73259
	.byte 	$ae,$80
	.byte 	1     ; *** Load Float -237.63 ***
	.dword 	$eda147ae
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 197547153046.36624 ***
	.dword 	$b7fae95a
	.byte 	$a6,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.408657 ***
	.dword 	$9a276fb0
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 9.175055 ***
	.dword 	$92cd0678
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.766398000000001 ***
	.dword 	$d8865519
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.48 ***
	.dword 	$d7ae147a
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 17.48 ***
	.dword 	$8bd70a3d
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 12727154954762.977 ***
	.dword 	$b93458cd
	.byte 	$ac,$0
	.byte 	1     ; *** Load Float 3.5575714111328124e-06 ***
	.dword 	$eebe9c88
	.byte 	$6e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 45277762.61212209 ***
	.dword 	$acb890a7
	.byte 	$9a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 841.41 ***
	.dword 	$d25a3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -6273957.363712 ***
	.dword 	$bf774aba
	.byte 	$97,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5278970465.400913 ***
	.dword 	$9d535930
	.byte 	$a1,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -25246123979876.336 ***
	.dword 	$b7b09203
	.byte 	$ad,$80
	.byte 	1     ; *** Load Float 4.277935659047216e-13 ***
	.dword 	$f0d38cda
	.byte 	$57,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -25246123979876.336 ***
	.dword 	$b7b09203
	.byte 	$ad,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.9620051383972168e-08 ***
	.dword 	$fe6f2e8c
	.byte 	$67,$0
	.byte 	1     ; *** Load Float 9.358227 ***
	.dword 	$95bb4c3c
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -9.358226970379947 ***
	.dword 	$95bb4c34
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.49536620080471e-10 ***
	.dword 	$e984d338
	.byte 	$62,$80
	.byte 	1     ; *** Load Float 3.630706 ***
	.dword 	$e85d7cb2
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -52.0 ***
	.dword 	$d0000000
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.214645 ***
	.dword 	$e6de5f30
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.689393 ***
	.dword 	$b07c0f45
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -785.82 ***
	.dword 	$c4747ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3143.28 ***
	.dword 	$c4747ae1
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.386415639601182e-13 ***
	.dword 	$f6eee957
	.byte 	$57,$80
	.byte 	1     ; *** Load Float -164.52 ***
	.dword 	$a4851eb8
	.byte 	$88,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 164.51999999999958 ***
	.dword 	$a4851eb8
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 958.39 ***
	.dword 	$ef98f5c2
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 509213470.09740806 ***
	.dword 	$f2cfd8f0
	.byte 	$9d,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 509214428.48740804 ***
	.dword 	$f2cff6e3
	.byte 	$9d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -120150507514.75711 ***
	.dword 	$dfcc39ff
	.byte 	$a5,$80
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -120150507526.75711 ***
	.dword 	$dfcc3a00
	.byte 	$a5,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -2.3107859306037425e-12 ***
	.dword 	$a29b6b2a
	.byte 	$5a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1731012789642.0566 ***
	.dword 	$c9843382
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -363.12 ***
	.dword 	$b58f5c28
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -363.12 ***
	.dword 	$b58f5c28
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.714794921875e-05 ***
	.dword 	$8cd1c7de
	.byte 	$73,$80
	.byte 	1     ; *** Load Float 9.209588170051575e-10 ***
	.dword 	$fd26b723
	.byte 	$62,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -72910.91412437605 ***
	.dword 	$8e677502
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1054169967269.7733 ***
	.dword 	$f5716d2a
	.byte 	$a8,$0
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1054169967261.7733 ***
	.dword 	$f5716d2a
	.byte 	$a8,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -696.91 ***
	.dword 	$ae3a3d70
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 559.81 ***
	.dword 	$8bf3d70a
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.244904521176828 ***
	.dword 	$9f590806
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 251715471847968.47 ***
	.dword 	$e4ef1348
	.byte 	$b0,$0
	.byte 	1     ; *** Load Float -20715291648509.082 ***
	.dword 	$96b93ccd
	.byte 	$ad,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5.214359411772744e+27 ***
	.dword 	$86c9bc70
	.byte 	$dd,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.02369 ***
	.dword 	$906108c3
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 3.3690639611450024e-14 ***
	.dword 	$97baa9b4
	.byte 	$54,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3.040138877554455e-13 ***
	.dword 	$ab2504c3
	.byte 	$57,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 6.205896 ***
	.dword 	$c696b335
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.730136 ***
	.dword 	$f75d462c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -7.269864 ***
	.dword 	$e8a2b9d3
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.487356 ***
	.dword 	$8f986b9c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.950780421495438e-10 ***
	.dword 	$88160525
	.byte 	$62,$0
	.byte 	1     ; *** Load Float 0.504268 ***
	.dword 	$8117b528
	.byte 	$80,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 9.817756473731105e-10 ***
	.dword 	$86ef28e1
	.byte 	$63,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -25112915947148.016 ***
	.dword 	$b6b87379
	.byte 	$ad,$80
	.byte 	1     ; *** Load Float -25112915947148.016 ***
	.dword 	$b6b87379
	.byte 	$ad,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -50225831894296.03 ***
	.dword 	$b6b87379
	.byte 	$ae,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 8.968687 ***
	.dword 	$8f7fbdf0
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2.2299808210499488 ***
	.dword 	$8eb8017a
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.533866 ***
	.dword 	$91156e26
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 660.04 ***
	.dword 	$a5028f5c
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 664.573866 ***
	.dword 	$a624ba38
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.63934651911768e-16 ***
	.dword 	$9825e13b
	.byte 	$4d,$80
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.3994059264706182e-17 ***
	.dword 	$dd4e5ee1
	.byte 	$49,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 1966692050556.4202 ***
	.dword 	$e4f3fd93
	.byte 	$a9,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -8.135488215083419e-12 ***
	.dword 	$8f1efb50
	.byte 	$5c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -903.63 ***
	.dword 	$e1e851eb
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -5.7561777566661476e-15 ***
	.dword 	$cf635e74
	.byte 	$51,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.19213 ***
	.dword 	$8312f6e8
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 6.719383 ***
	.dword 	$d7052f7f
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1.472747000000001 ***
	.dword 	$bc82f944
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 460.35 ***
	.dword 	$e62ccccc
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 6.131926 ***
	.dword 	$c438bcdf
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 454.218074 ***
	.dword 	$e31be9d9
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.890593 ***
	.dword 	$8e3fde72
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.886671144457069e-14 ***
	.dword 	$9b12f4cf
	.byte 	$55,$0
	.byte 	1     ; *** Load Float -42.59 ***
	.dword 	$aa5c28f5
	.byte 	$86,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.9330332404242655e-12 ***
	.dword 	$ce64d462
	.byte 	$5a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 313.64 ***
	.dword 	$9cd1eb85
	.byte 	$89,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.812952 ***
	.dword 	$d01d9f4d
	.byte 	$80,$0
	.byte 	1     ; *** Load Float -2.721048891544342e-09 ***
	.dword 	$bafd32c6
	.byte 	$64,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.8129519972789511 ***
	.dword 	$d01d9f41
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 8.152494 ***
	.dword 	$82709d8c
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -16.304988 ***
	.dword 	$82709d8c
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.198378 ***
	.dword 	$cb239a38
	.byte 	$7e,$80
	.byte 	1     ; *** Load Float -7.105588912963868e-09 ***
	.dword 	$f4256bca
	.byte 	$65,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 27918586.682951376 ***
	.dword 	$d5007d57
	.byte 	$99,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.05427 ***
	.dword 	$90de4a38
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 52456918.614016 ***
	.dword 	$c81b75a7
	.byte 	$9a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 52456927.668285996 ***
	.dword 	$c81b77ea
	.byte 	$9a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.784002 ***
	.dword 	$b9168b5c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1533163411817.3655 ***
	.dword 	$b27bd48c
	.byte 	$a9,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 59.31 ***
	.dword 	$ed3d70a3
	.byte 	$86,$0
	.byte 	1     ; *** Load Float 5.8786630630493167e-08 ***
	.dword 	$fc7c957c
	.byte 	$68,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 312.29 ***
	.dword 	$9c251eb8
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 5.750751495361328e-07 ***
	.dword 	$9a5edd05
	.byte 	$6c,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0001795902184486389 ***
	.dword 	$bc5061d6
	.byte 	$74,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.154348 ***
	.dword 	$9e0d66f0
	.byte 	$7e,$0
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 1.960638427734375e-05 ***
	.dword 	$a47863be
	.byte 	$71,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 191.64 ***
	.dword 	$bfa3d70a
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 383.36 ***
	.dword 	$bfae147a
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 73467.11039999999 ***
	.dword 	$8f7d8e21
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.929931640625e-05 ***
	.dword 	$a4d551d6
	.byte 	$72,$0
	.byte 	1     ; *** Load Float -133.92 ***
	.dword 	$85eb851e
	.byte 	$88,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 0.895244 ***
	.dword 	$e52eb5f5
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.687461 ***
	.dword 	$9affd71b
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 9.687461 ***
	.dword 	$9affd71b
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.811296771047637e-14 ***
	.dword 	$996073de
	.byte 	$55,$0
	.byte 	1     ; *** Load Float -942.25 ***
	.dword 	$eb900000
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -7.228757517694493e-17 ***
	.dword 	$a6af0d82
	.byte 	$4b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -489.64 ***
	.dword 	$f4d1eb85
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 420.12 ***
	.dword 	$d20f5c28
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -69.51999999999998 ***
	.dword 	$8b0a3d70
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -855.36 ***
	.dword 	$d5d70a3d
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -851.36 ***
	.dword 	$d4d70a3d
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 1.539257610261302e-15 ***
	.dword 	$ddd49518
	.byte 	$4f,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.539257610261302e-15 ***
	.dword 	$ddd49518
	.byte 	$4f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 9.779237 ***
	.dword 	$9c77c137
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -58.675422 ***
	.dword 	$eab3a1d3
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.729794941842556e-10 ***
	.dword 	$961272c9
	.byte 	$61,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 692.65 ***
	.dword 	$ad299999
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.896953 ***
	.dword 	$e59eb639
	.byte 	$80,$80
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 4.484765 ***
	.dword 	$8f8331e3
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.29292 ***
	.dword 	$95f99c38
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -0.889042 ***
	.dword 	$e39841aa
	.byte 	$80,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.3294782473718902 ***
	.dword 	$a8b15f72
	.byte 	$7f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 6.764846 ***
	.dword 	$d8799e51
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 13.764846 ***
	.dword 	$dc3ccf28
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -386.42 ***
	.dword 	$c135c28f
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 2540.408832 ***
	.dword 	$9ec68a93
	.byte 	$8c,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -2926.828832 ***
	.dword 	$b6ed42e5
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 965.59 ***
	.dword 	$f165c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 946.59 ***
	.dword 	$eca5c28f
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 720.11 ***
	.dword 	$b4070a3d
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 697.3 ***
	.dword 	$ae533333
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -857.48 ***
	.dword 	$d65eb851
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -605.62 ***
	.dword 	$9767ae14
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -251.86 ***
	.dword 	$fbdc28f5
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.132324 ***
	.dword 	$821dffc5
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 56294995342.1312 ***
	.dword 	$d1b71758
	.byte 	$a4,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 593.51 ***
	.dword 	$9460a3d7
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 8.471019441458339e-15 ***
	.dword 	$9899ae92
	.byte 	$52,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 7.0063586101016376e+16 ***
	.dword 	$f8ea75d9
	.byte 	$b8,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.69017 ***
	.dword 	$b0aefb2a
	.byte 	$80,$80
	.byte 	1     ; *** Load Float -0.434383 ***
	.dword 	$de6772d5
	.byte 	$7f,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1.124553 ***
	.dword 	$8ff15a4a
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.494173 ***
	.dword 	$afd043e5
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 627.65 ***
	.dword 	$9ce99999
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.354919 ***
	.dword 	$cb5b7f17
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 256.91 ***
	.dword 	$80747ae1
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.02473597368728348 ***
	.dword 	$caa318c0
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -481.98 ***
	.dword 	$f0fd70a3
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -71176885224.07936 ***
	.dword 	$8493c89f
	.byte 	$a5,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 71176884742.09937 ***
	.dword 	$8493c890
	.byte 	$a5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.230937 ***
	.dword 	$93b1eafe
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.230937 ***
	.dword 	$93b1eafe
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 25.0 ***
	.dword 	$c8000000
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 530.0 ***
	.dword 	$84800000
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 550.0 ***
	.dword 	$89800000
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -304.85 ***
	.dword 	$986ccccc
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 43.550000000000004 ***
	.dword 	$ae333333
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 685.25 ***
	.dword 	$ab500000
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -679.25 ***
	.dword 	$a9d00000
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -258894.987264 ***
	.dword 	$fcd3bf2f
	.byte 	$92,$80
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -258902.987264 ***
	.dword 	$fcd5bf2f
	.byte 	$92,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.976849 ***
	.dword 	$ff4258d5
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -896.39 ***
	.dword 	$e018f5c2
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.008898859871261393 ***
	.dword 	$91cc8607
	.byte 	$7a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.837642 ***
	.dword 	$bacdf698
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 52.538778 ***
	.dword 	$d227b56b
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 834.16 ***
	.dword 	$d08a3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -187210977335094.28 ***
	.dword 	$aa4473cd
	.byte 	$b0,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -4.45572162420216e-12 ***
	.dword 	$9cc5928e
	.byte 	$5b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 573.12 ***
	.dword 	$8f47ae14
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.869289 ***
	.dword 	$fbd1372a
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -11934580244.217855 ***
	.dword 	$b1d6cf85
	.byte 	$a2,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -93916661035.44089 ***
	.dword 	$aeeef429
	.byte 	$a5,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.40494 ***
	.dword 	$cf544bb1
	.byte 	$7f,$0
	.byte 	1     ; *** Load Float 0.40494 ***
	.dword 	$cf544bb1
	.byte 	$7f,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.880757 ***
	.dword 	$9e1794a6
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -512532947241.2713 ***
	.dword 	$eeaab042
	.byte 	$a7,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 512532947251.15204 ***
	.dword 	$eeaab042
	.byte 	$a7,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -463.81 ***
	.dword 	$e7e7ae14
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -1.8030004866886884e-13 ***
	.dword 	$cafff36a
	.byte 	$56,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.13012 ***
	.dword 	$c853e2d6
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -888.49 ***
	.dword 	$de1f5c28
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -885.35988 ***
	.dword 	$dd570846
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3500901.66272 ***
	.dword 	$d5ad96a6
	.byte 	$96,$80
	.byte 	1     ; *** Load Float -252.61 ***
	.dword 	$fc9c28f5
	.byte 	$88,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -3501154.27272 ***
	.dword 	$d5b18917
	.byte 	$96,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -988.07 ***
	.dword 	$f7047ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -982.07 ***
	.dword 	$f5847ae1
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6429624.762368 ***
	.dword 	$c4377186
	.byte 	$97,$0
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -918517.8231954286 ***
	.dword 	$e03f5d2b
	.byte 	$94,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4773.134336 ***
	.dword 	$9529131e
	.byte 	$8d,$0
	.byte 	1     ; *** Load Float 8.806359 ***
	.dword 	$8ce6d8b1
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4781.940695 ***
	.dword 	$956f868b
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.296954 ***
	.dword 	$94c052d6
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -840.2350080000001 ***
	.dword 	$d20f0a5e
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 2.539088 ***
	.dword 	$a2806af4
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -842.7740960000001 ***
	.dword 	$d2b18ac9
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.719478 ***
	.dword 	$9b82fb5d
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -136.07269200000002 ***
	.dword 	$88129bf1
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.123761 ***
	.dword 	$c7ebb341
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.427363 ***
	.dword 	$8dacf52b
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0698020923882723e-10 ***
	.dword 	$eb4080f9
	.byte 	$5f,$0
	.byte 	1     ; *** Load Float -482.35 ***
	.dword 	$f12ccccc
	.byte 	$89,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5.160190392634832e-08 ***
	.dword 	$dda0e4b4
	.byte 	$68,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7139086049.476608 ***
	.dword 	$d4c2e770
	.byte 	$a1,$80
	.byte 	1     ; *** Load Float -1.2248373031616212e-07 ***
	.dword 	$83841248
	.byte 	$6a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -7139086049.476608 ***
	.dword 	$d4c2e770
	.byte 	$a1,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 34.8 ***
	.dword 	$8b333333
	.byte 	$86,$0
	.byte 	1     ; *** Load Float 34.8 ***
	.dword 	$8b333333
	.byte 	$86,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.003383 ***
	.dword 	$c0376d54
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -468.35 ***
	.dword 	$ea2ccccc
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 471.353383 ***
	.dword 	$ebad3ba7
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -368777.88774399995 ***
	.dword 	$b4113c68
	.byte 	$93,$80
	.byte 	1     ; *** Load Float -801.94 ***
	.dword 	$c87c28f5
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -367975.94774399995 ***
	.dword 	$b3acfe53
	.byte 	$93,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.452804 ***
	.dword 	$e7d5ed06
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.452804 ***
	.dword 	$e7d5ed06
	.byte 	$7f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.504669189453125e-06 ***
	.dword 	$a815e397
	.byte 	$6e,$80
	.byte 	1     ; *** Load Float -989.93 ***
	.dword 	$f77b851e
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -989.9300025046691 ***
	.dword 	$f77b8529
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3832035517310.96 ***
	.dword 	$df0dc768
	.byte 	$aa,$80
	.byte 	1     ; *** Load Float 2.689217 ***
	.dword 	$ac1c219e
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -419390396949482.94 ***
	.dword 	$beb777d0
	.byte 	$b1,$80
	.byte 	1     ; *** Load Float 4.298846435546875e-05 ***
	.dword 	$b44e831a
	.byte 	$72,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -18028949130.28874 ***
	.dword 	$86537dd1
	.byte 	$a3,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -682.72 ***
	.dword 	$aaae147a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 1.43928 ***
	.dword 	$b83a53b8
	.byte 	$81,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -681.28072 ***
	.dword 	$aa51f751
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 173.69 ***
	.dword 	$adb0a3d7
	.byte 	$88,$0
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 184.69 ***
	.dword 	$b8b0a3d7
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.806277 ***
	.dword 	$e73415b1
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.3660926818847654e-06 ***
	.dword 	$9ec929aa
	.byte 	$6e,$80
	.byte 	1     ; *** Load Float -673.84 ***
	.dword 	$a875c28f
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.253579 ***
	.dword 	$e81d51b4
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 7.253579 ***
	.dword 	$e81d51b4
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 694.58 ***
	.dword 	$ada51eb8
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -589.06 ***
	.dword 	$9343d70a
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1283.6399999999999 ***
	.dword 	$a0747ae1
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -6167.1342079999995 ***
	.dword 	$c0b912db
	.byte 	$8d,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.003242997367246528 ***
	.dword 	$d48877a2
	.byte 	$78,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 108.0 ***
	.dword 	$d8000000
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 6.123364926224894e-15 ***
	.dword 	$dc9e12a5
	.byte 	$51,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3.999999999999994 ***
	.dword 	$ffffffff
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 5812600.700928001 ***
	.dword 	$b162f166
	.byte 	$97,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.5483602716015089e-06 ***
	.dword 	$cfd140fb
	.byte 	$6d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -798.37 ***
	.dword 	$c797ae14
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 794.37 ***
	.dword 	$c697ae14
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 4.993364 ***
	.dword 	$9fc9a34c
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 24.993364 ***
	.dword 	$c7f268d3
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.71016 ***
	.dword 	$ad7342ed
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -1.4956871297044927e-15 ***
	.dword 	$d78d1d8a
	.byte 	$4f,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -4.053551431439928e-15 ***
	.dword 	$920b69b5
	.byte 	$51,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.647102 ***
	.dword 	$a5a87a07
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 4.790885 ***
	.dword 	$994eee0f
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.143783 ***
	.dword 	$8499dece
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 841.68 ***
	.dword 	$d26b851e
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -220.81 ***
	.dword 	$dccf5c28
	.byte 	$88,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -185851.3608 ***
	.dword 	$b57ed717
	.byte 	$92,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.041524 ***
	.dword 	$82a85447
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 719276.998656 ***
	.dword 	$af9acffa
	.byte 	$94,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1468421.2554041918 ***
	.dword 	$b3402a0b
	.byte 	$95,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.046746 ***
	.dword 	$817ef177
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.235560620804963 ***
	.dword 	$9e26d9b5
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.304873 ***
	.dword 	$9c185058
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float 9.641262 ***
	.dword 	$9a429bf1
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9.336388999999999 ***
	.dword 	$9561d96e
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -159883378.819072 ***
	.dword 	$987a072d
	.byte 	$9c,$80
	.byte 	1     ; *** Load Float -3.6730691790580746e-09 ***
	.dword 	$fc6950fc
	.byte 	$64,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.587262710984 ***
	.dword 	$9656d959
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.865605 ***
	.dword 	$8dd984a0
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 4.134395 ***
	.dword 	$844cf6be
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.911598469130695e-12 ***
	.dword 	$89a08bfc
	.byte 	$5b,$80
	.byte 	1     ; *** Load Float -3.911598469130695e-12 ***
	.dword 	$89a08bfc
	.byte 	$5b,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -649.74 ***
	.dword 	$a26f5c28
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 156.03 ***
	.dword 	$9c07ae14
	.byte 	$88,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -101378.9322 ***
	.dword 	$c6017752
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.556978 ***
	.dword 	$98e961c3
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.5928296666666668 ***
	.dword 	$cbe1d7af
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 380.18 ***
	.dword 	$be170a3d
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 6.790196 ***
	.dword 	$d949491f
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 373.389804 ***
	.dword 	$bab1e518
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.090585 ***
	.dword 	$b984a0e4
	.byte 	$7d,$80
	.byte 	1     ; *** Load Float 5.415273 ***
	.dword 	$ad49ea9a
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -5.505858 ***
	.dword 	$b02ffd1d
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.386714 ***
	.dword 	$c5ff609d
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.4179 ***
	.dword 	$86afb7e9
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -453.23 ***
	.dword 	$e29d70a3
	.byte 	$89,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.083335 ***
	.dword 	$85555c52
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -740.07 ***
	.dword 	$b9047ae1
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0028150512789330735 ***
	.dword 	$b87cb92d
	.byte 	$78,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -727.0 ***
	.dword 	$b5c00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -727.0 ***
	.dword 	$b5c00000
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.778009653091431e-08 ***
	.dword 	$cd36c58e
	.byte 	$68,$0
	.byte 	1     ; *** Load Float -891.12 ***
	.dword 	$dec7ae14
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -891.1199999522199 ***
	.dword 	$dec7ae14
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.52952 ***
	.dword 	$f0f1d3ed
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 272.16 ***
	.dword 	$88147ae1
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 279.68952 ***
	.dword 	$8bd84230
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -154.24 ***
	.dword 	$9a3d70a3
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -5.8734044432640075e-09 ***
	.dword 	$c9cf0307
	.byte 	$65,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9.059139013290405e-07 ***
	.dword 	$f32dede4
	.byte 	$6c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 270.95 ***
	.dword 	$87799999
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 5.843155086040496e-09 ***
	.dword 	$c8c4ef88
	.byte 	$65,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 270.95000000584315 ***
	.dword 	$87799999
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -3.99 ***
	.dword 	$ff5c28f5
	.byte 	$82,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 10.99 ***
	.dword 	$afd70a3d
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.3267504306877524e-15 ***
	.dword 	$efb7b6bb
	.byte 	$50,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1.9960502584126514e-14 ***
	.dword 	$b3c9c90c
	.byte 	$53,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -881.07 ***
	.dword 	$dc447ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 5.06454 ***
	.dword 	$a210b630
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -886.13454 ***
	.dword 	$dd889c4d
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.324098 ***
	.dword 	$a97c0b13
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -103897480453483.94 ***
	.dword 	$bcfd08d4
	.byte 	$af,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -137570446073497.17 ***
	.dword 	$fa3d3b23
	.byte 	$af,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 0.000146513427734375 ***
	.dword 	$99a16616
	.byte 	$74,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 29879986.814976 ***
	.dword 	$e3f75968
	.byte 	$99,$0
	.byte 	1     ; *** Load Float -2104474051656.2864 ***
	.dword 	$f4fe36d2
	.byte 	$a9,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 2104503931643.1013 ***
	.dword 	$f4ff1ac9
	.byte 	$a9,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -47457103285881.664 ***
	.dword 	$aca5df22
	.byte 	$ae,$80
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -47457103285865.664 ***
	.dword 	$aca5df22
	.byte 	$ae,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -814.52 ***
	.dword 	$cba147ae
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 6.515525 ***
	.dword 	$d07f2e48
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 110.54 ***
	.dword 	$dd147ae1
	.byte 	$87,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 103.54 ***
	.dword 	$cf147ae1
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 2.53197 ***
	.dword 	$a20bcbe6
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -8.53197 ***
	.dword 	$8882f2f9
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -125676606776470.94 ***
	.dword 	$e49abb01
	.byte 	$af,$80
	.byte 	1     ; *** Load Float 9.19416 ***
	.dword 	$931b4784
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.61614 ***
	.dword 	$b3b76b3b
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 2.8052994593963376e-14 ***
	.dword 	$fcadcd2d
	.byte 	$53,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 5.616139999999971 ***
	.dword 	$b3b76b3b
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 224652215787.19232 ***
	.dword 	$d1394317
	.byte 	$a6,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.676987336821614e-11 ***
	.dword 	$92d418db
	.byte 	$5f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -0.00070759765625 ***
	.dword 	$b97e132b
	.byte 	$76,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.00070759765625 ***
	.dword 	$b97e132b
	.byte 	$76,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 924.08 ***
	.dword 	$e7051eb8
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 3607269.21216 ***
	.dword 	$dc2b94d9
	.byte 	$96,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 3608193.29216 ***
	.dword 	$dc3a052b
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 75.26 ***
	.dword 	$96851eb8
	.byte 	$87,$0
	.byte 	1     ; *** Load Float -325708844.89216 ***
	.dword 	$9b4f6167
	.byte 	$9d,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -325708769.63216 ***
	.dword 	$9b4f5f0d
	.byte 	$9d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -7.1927978515625e-05 ***
	.dword 	$96d80a17
	.byte 	$73,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -7.1927978515625e-05 ***
	.dword 	$96d80a17
	.byte 	$73,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 882.62 ***
	.dword 	$dca7ae14
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 456040.382464 ***
	.dword 	$dead0c3d
	.byte 	$93,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0019353987803254996 ***
	.dword 	$fdad34ee
	.byte 	$77,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 2.243527 ***
	.dword 	$8f95f245
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -22.243527 ***
	.dword 	$b1f2be48
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 643.61 ***
	.dword 	$a0e70a3d
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 643.61 ***
	.dword 	$a0e70a3d
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1287.22 ***
	.dword 	$a0e70a3d
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.406556 ***
	.dword 	$868140dd
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -1543527494.320128 ***
	.dword 	$b800b88c
	.byte 	$9f,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -12975750318.541838 ***
	.dword 	$c15a8f2b
	.byte 	$a2,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.516975 ***
	.dword 	$98458793
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -3.4830249999999996 ***
	.dword 	$dee9e1b0
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.838939 ***
	.dword 	$bad8969a
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 2.0701179437310204e-14 ***
	.dword 	$ba75ab7d
	.byte 	$53,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.013391 ***
	.dword 	$9036d97b
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.838908 ***
	.dword 	$9d6c2acb
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.9160966847133849 ***
	.dword 	$ea854ff4
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.6220519682974556e-13 ***
	.dword 	$b6a07703
	.byte 	$56,$0
	.byte 	1     ; *** Load Float 6.920344 ***
	.dword 	$dd737542
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 246975151765184.3 ***
	.dword 	$e09f6230
	.byte 	$b0,$0
	.byte 	1     ; *** Load Float 5.033973 ***
	.dword 	$a1164e8b
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 246975151765179.28 ***
	.dword 	$e09f6230
	.byte 	$b0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.325436 ***
	.dword 	$aa69f8c2
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -0.0004145625 ***
	.dword 	$d959a309
	.byte 	$75,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -12845.918287351124 ***
	.dword 	$c8b7ac53
	.byte 	$8e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.206715 ***
	.dword 	$869d68c6
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 5.747479 ***
	.dword 	$b7eb5914
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 815.49 ***
	.dword 	$cbdf5c28
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.4933776855468752e-06 ***
	.dword 	$c870110a
	.byte 	$6d,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 815.4899985066223 ***
	.dword 	$cbdf5c22
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.03322 ***
	.dword 	$84408d8e
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -3.9965612813830375e-11 ***
	.dword 	$afc5479d
	.byte 	$5e,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -132218.88 ***
	.dword 	$811eb851
	.byte 	$92,$80
	.byte 	1     ; *** Load Float 381662054021140.06 ***
	.dword 	$ad8f4f93
	.byte 	$b1,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -5.046292932117464e+19 ***
	.dword 	$af1415b6
	.byte 	$c2,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
