; Using seed 599048
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -608.13 ***
	.dword 	$980851eb
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.5876041036099197e-11 ***
	.dword 	$e39baa15
	.byte 	$5d,$0
	.byte 	1     ; *** Load Float 2.5876041036099197e-11 ***
	.dword 	$e39baa15
	.byte 	$5d,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 2.925364 ***
	.dword 	$bb3929ed
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -17.074635999999998 ***
	.dword 	$8898dac2
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.54504 ***
	.dword 	$e2e1ef73
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 19163731757.891586 ***
	.dword 	$8ec7eae5
	.byte 	$a3,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -19163731754.346546 ***
	.dword 	$8ec7eae5
	.byte 	$a3,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.2973994016647338e-09 ***
	.dword 	$b2502eec
	.byte 	$63,$0
	.byte 	1     ; *** Load Float 1.2973994016647338e-09 ***
	.dword 	$b2502eec
	.byte 	$63,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 802.35 ***
	.dword 	$c8966666
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -1.4013153304404115e-14 ***
	.dword 	$fc70435e
	.byte 	$52,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 911.75 ***
	.dword 	$e3f00000
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 2.5403714971616864e-11 ***
	.dword 	$df7414a4
	.byte 	$5d,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 911.7499999999746 ***
	.dword 	$e3efffff
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 265540115329112.38 ***
	.dword 	$f181e03f
	.byte 	$b0,$0
	.byte 	1     ; *** Load Float 690.25 ***
	.dword 	$ac900000
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 384701362302.2273 ***
	.dword 	$b323f9e0
	.byte 	$a7,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.916836 ***
	.dword 	$bd56b873
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 727.52 ***
	.dword 	$b5e147ae
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.008132884319331428 ***
	.dword 	$853fca0b
	.byte 	$7a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.496695282796281e-14 ***
	.dword 	$ca835ded
	.byte 	$54,$0
	.byte 	1     ; *** Load Float 1.833612 ***
	.dword 	$eab3cc4a
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -2779969121.943552 ***
	.dword 	$a5b2f661
	.byte 	$a0,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -483893564.145664 ***
	.dword 	$e6bd09e1
	.byte 	$9d,$80
	.byte 	1     ; *** Load Float 1.4506906270980834e-08 ***
	.dword 	$f93a0c6b
	.byte 	$66,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -483893564.145664 ***
	.dword 	$e6bd09e1
	.byte 	$9d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.473014 ***
	.dword 	$9e45dc83
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 361.89 ***
	.dword 	$b4f1eb85
	.byte 	$89,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 894.95903646 ***
	.dword 	$dfbd60da
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -687.0 ***
	.dword 	$abc00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.076163158586496e-15 ***
	.dword 	$9b1769a9
	.byte 	$4f,$80
	.byte 	1     ; *** Load Float 8.130969 ***
	.dword 	$821872f3
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 224.46 ***
	.dword 	$e075c28f
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 2007276.453888 ***
	.dword 	$f50763a1
	.byte 	$95,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 450553272.8397005 ***
	.dword 	$d6d72dc6
	.byte 	$9d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -8.442214965820313e-06 ***
	.dword 	$8da30984
	.byte 	$70,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 8.442214965820313e-06 ***
	.dword 	$8da30984
	.byte 	$70,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2572259074670.33 ***
	.dword 	$95b9a5a8
	.byte 	$aa,$80
	.byte 	1     ; *** Load Float -2572259074670.33 ***
	.dword 	$95b9a5a8
	.byte 	$aa,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.3271280699409548e-12 ***
	.dword 	$ea203600
	.byte 	$5a,$80
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -166.84 ***
	.dword 	$a6d70a3d
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 11.917142857142858 ***
	.dword 	$beac9dfd
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.024785 ***
	.dword 	$cb09e98d
	.byte 	$7b,$80
	.byte 	1     ; *** Load Float 8664458.985472001 ***
	.dword 	$84358afc
	.byte 	$98,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -8664459.010257002 ***
	.dword 	$84358b02
	.byte 	$98,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.686379 ***
	.dword 	$d7db445e
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 303.55 ***
	.dword 	$97c66666
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.005555522978092572 ***
	.dword 	$b60b1ac0
	.byte 	$79,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.531689 ***
	.dword 	$881cc532
	.byte 	$80,$0
	.byte 	1     ; *** Load Float 343.48 ***
	.dword 	$abbd70a3
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -342.94831100000005 ***
	.dword 	$ab796241
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.6797985881567e-09 ***
	.dword 	$e6dea897
	.byte 	$63,$80
	.byte 	1     ; *** Load Float -853.13 ***
	.dword 	$d54851eb
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.9689831422604997e-12 ***
	.dword 	$8a8e0c07
	.byte 	$5a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 287.22 ***
	.dword 	$8f9c28f5
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 363.85 ***
	.dword 	$b5eccccc
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 651.07 ***
	.dword 	$a2c47ae1
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.491289138793945e-07 ***
	.dword 	$ae3fcc9e
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float 340.402176 ***
	.dword 	$aa337a80
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 340.40217664912893 ***
	.dword 	$aa337a86
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -175.65 ***
	.dword 	$afa66666
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 9.832517 ***
	.dword 	$9d51fd58
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -185.482517 ***
	.dword 	$b97b863b
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 515.55 ***
	.dword 	$80e33333
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -2.731794666033238e-13 ***
	.dword 	$99c94f69
	.byte 	$57,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 515.5500000000002 ***
	.dword 	$80e33333
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.00045486279296875 ***
	.dword 	$ee7aa68f
	.byte 	$75,$0
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.498944561298077e-05 ***
	.dword 	$92c1a193
	.byte 	$72,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.00023545605468750002 ***
	.dword 	$f6e4c0df
	.byte 	$74,$80
	.byte 	1     ; *** Load Float -189.92 ***
	.dword 	$bdeb851e
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.2397643991549074e-06 ***
	.dword 	$a665fafb
	.byte 	$6d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -676.13 ***
	.dword 	$a90851eb
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -685.13 ***
	.dword 	$ab4851eb
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -878.59 ***
	.dword 	$dba5c28f
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -969.62 ***
	.dword 	$f267ae14
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 138.76 ***
	.dword 	$8ac28f5c
	.byte 	$88,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.9877486307293175 ***
	.dword 	$df9ba304
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5146914.32448 ***
	.dword 	$9d1244a6
	.byte 	$97,$80
	.byte 	1     ; *** Load Float 17684.168704 ***
	.dword 	$8a285660
	.byte 	$8f,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -5129230.155776 ***
	.dword 	$9c881c4f
	.byte 	$97,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 932.528128 ***
	.dword 	$e921ccd9
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -0.780464 ***
	.dword 	$c7cc7d1b
	.byte 	$80,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -727.8046328913921 ***
	.dword 	$b5f37f1a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 25.66 ***
	.dword 	$cd47ae14
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 197.58 ***
	.dword 	$c5947ae1
	.byte 	$88,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -171.92000000000002 ***
	.dword 	$abeb851e
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -30655721188534.258 ***
	.dword 	$df0cbaf9
	.byte 	$ad,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.884335 ***
	.dword 	$8e263c74
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 30570187979986.305 ***
	.dword 	$de6d698f
	.byte 	$ad,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 30570187979995.188 ***
	.dword 	$de6d698f
	.byte 	$ad,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -90.0 ***
	.dword 	$b4000000
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -265.99 ***
	.dword 	$84feb851
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 470.6 ***
	.dword 	$eb4ccccc
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 204.61 ***
	.dword 	$cc9c28f5
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.482667 ***
	.dword 	$f7202107
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -295495.008256 ***
	.dword 	$9048e043
	.byte 	$93,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -295495.490923 ***
	.dword 	$9048efb5
	.byte 	$93,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.607256 ***
	.dword 	$cdba908a
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 213997.060096 ***
	.dword 	$d0fb43d8
	.byte 	$92,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -213995.45284 ***
	.dword 	$d0fadcfb
	.byte 	$92,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -703.5 ***
	.dword 	$afe00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -513.5 ***
	.dword 	$80600000
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.3700097370983446 ***
	.dword 	$af5c7aa4
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -258.32 ***
	.dword 	$8128f5c2
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1291.6 ***
	.dword 	$a1733333
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.890257 ***
	.dword 	$8e3e7e1f
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -592.55 ***
	.dword 	$94233333
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 601.440257 ***
	.dword 	$965c2d2b
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -306988.97408 ***
	.dword 	$95e59f2b
	.byte 	$93,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5.5376581686513186e-05 ***
	.dword 	$e84426de
	.byte 	$72,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.272843 ***
	.dword 	$8bb213e3
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -0.272843 ***
	.dword 	$8bb213e3
	.byte 	$7f,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -0.545686 ***
	.dword 	$8bb213e3
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 1130364525.346816 ***
	.dword 	$86bffcda
	.byte 	$9f,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 18085832405.549057 ***
	.dword 	$86bffcda
	.byte 	$a3,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.92918 ***
	.dword 	$eddebd90
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 4.816392902284861e-12 ***
	.dword 	$a97635e7
	.byte 	$5b,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -0.9291800000048164 ***
	.dword 	$eddebd90
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -296.17 ***
	.dword 	$9415c28f
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -3.286814689636231e-08 ***
	.dword 	$8d2ae8e1
	.byte 	$68,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 9.734559066295625e-06 ***
	.dword 	$a3519ce2
	.byte 	$70,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 686.68 ***
	.dword 	$abab851e
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 5.517011 ***
	.dword 	$b08b5aa7
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 84920859736116.56 ***
	.dword 	$9a785b5b
	.byte 	$af,$0
	.byte 	1     ; *** Load Float 154.53 ***
	.dword 	$9a87ae14
	.byte 	$88,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 84920859736271.1 ***
	.dword 	$9a785b5b
	.byte 	$af,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.867198437452317e-10 ***
	.dword 	$d8407cc7
	.byte 	$62,$80
	.byte 	1     ; *** Load Float 8.6277 ***
	.dword 	$8a0b0f27
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -6.787582795880736e-09 ***
	.dword 	$e93835ac
	.byte 	$65,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -168.0 ***
	.dword 	$a8000000
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 263.9 ***
	.dword 	$83f33333
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 1.610134 ***
	.dword 	$ce18def4
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 424.91436259999995 ***
	.dword 	$d47509d5
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.451797 ***
	.dword 	$9cea3df6
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -942.05 ***
	.dword 	$eb833333
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 692.91 ***
	.dword 	$ad3a3d70
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -249.14 ***
	.dword 	$f923d70a
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 70.93 ***
	.dword 	$8ddc28f5
	.byte 	$87,$0
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -5.910833333333334 ***
	.dword 	$bd258bf2
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.115974 ***
	.dword 	$83b60f1b
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.206917 ***
	.dword 	$d3e20ccf
	.byte 	$7e,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.8516649921579998 ***
	.dword 	$da06b788
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.274783 ***
	.dword 	$c8cb05b7
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -7.461891174316406e-07 ***
	.dword 	$c84db9c7
	.byte 	$6c,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 6.274783746189118 ***
	.dword 	$c8cb0748
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.85264 ***
	.dword 	$da469d73
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 363870.55206400005 ***
	.dword 	$b1abd1aa
	.byte 	$93,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.3432509038270065e-06 ***
	.dword 	$9d40be76
	.byte 	$6e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 416.03 ***
	.dword 	$d003d70a
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -809.69 ***
	.dword 	$ca6c28f5
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -3819.216896 ***
	.dword 	$eeb37867
	.byte 	$8c,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 57288.25344 ***
	.dword 	$dfc840e1
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1490.61632 ***
	.dword 	$ba53b8e4
	.byte 	$8b,$80
	.byte 	1     ; *** Load Float 8.401737 ***
	.dword 	$866d83c6
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1482.2145830000002 ***
	.dword 	$b946dddd
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.00011415173339843749 ***
	.dword 	$ef64bec6
	.byte 	$73,$80
	.byte 	1     ; *** Load Float -196014335930.1386 ***
	.dword 	$b68d759e
	.byte 	$a6,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 5.823642074787951e-16 ***
	.dword 	$a7dae4db
	.byte 	$4e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -7.4015426635742185e-06 ***
	.dword 	$f85ac471
	.byte 	$6f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 7.4015426635742185e-06 ***
	.dword 	$f85ac471
	.byte 	$6f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 828.99 ***
	.dword 	$cf3f5c28
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 1.655306 ***
	.dword 	$d3e11127
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.542651 ***
	.dword 	$a2bacb42
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.14956770588235296 ***
	.dword 	$992846d5
	.byte 	$7e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.549240112304688e-08 ***
	.dword 	$ee568a50
	.byte 	$68,$80
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.609463 ***
	.dword 	$ce02e232
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 4.0 ***
	.dword 	$80000000
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 6.437852 ***
	.dword 	$ce02e232
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5990543968402.67 ***
	.dword 	$ae5907d9
	.byte 	$ab,$80
	.byte 	1     ; *** Load Float 6.299572 ***
	.dword 	$c9961804
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -5990543968408.97 ***
	.dword 	$ae5907d9
	.byte 	$ab,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 23080912905901.703 ***
	.dword 	$a7ef8ceb
	.byte 	$ad,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 23080912905906.703 ***
	.dword 	$a7ef8ceb
	.byte 	$ad,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.461241 ***
	.dword 	$ec27c7c5
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -0.461241 ***
	.dword 	$ec27c7c5
	.byte 	$7f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.453754 ***
	.dword 	$9d0a4e37
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 709.5 ***
	.dword 	$b1600000
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -707.046246 ***
	.dword 	$b0c2f5b1
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -811.59 ***
	.dword 	$cae5c28f
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 791.59 ***
	.dword 	$c5e5c28f
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -701.09 ***
	.dword 	$af45c28f
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 0.844003 ***
	.dword 	$d81094a2
	.byte 	$80,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -701.9340030000001 ***
	.dword 	$af7bc6b4
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 4.049631 ***
	.dword 	$819693c0
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.429694 ***
	.dword 	$b7003686
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 2.960943 ***
	.dword 	$bd801711
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.390637 ***
	.dword 	$8c80192a
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -968.06 ***
	.dword 	$f203d70a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -16.4 ***
	.dword 	$83333333
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 59.02804878048781 ***
	.dword 	$ec1cb8d1
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.664641 ***
	.dword 	$9544bd33
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 3.311731 ***
	.dword 	$d3f36694
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.44757 ***
	.dword 	$87293f29
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 42.0 ***
	.dword 	$a8000000
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.428478 ***
	.dword 	$96db0bbf
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.539043 ***
	.dword 	$989feb8d
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -0.11056499999999936 ***
	.dword 	$e26fe718
	.byte 	$7d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -18352865.017856 ***
	.dword 	$8c057082
	.byte 	$99,$80
	.byte 	1     ; *** Load Float 4.832395 ***
	.dword 	$9aa2fad6
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -88688293.14796226 ***
	.dword 	$a928d4a4
	.byte 	$9b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.678751 ***
	.dword 	$d5b85404
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 926.98 ***
	.dword 	$e7beb851
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.007204849079807547 ***
	.dword 	$ec16a795
	.byte 	$79,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 4.624789 ***
	.dword 	$93fe4580
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.624789 ***
	.dword 	$93fe4580
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -657.11 ***
	.dword 	$a4470a3d
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.030436304423916847 ***
	.dword 	$f9558e83
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 236.95 ***
	.dword 	$ecf33333
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 236.95 ***
	.dword 	$ecf33333
	.byte 	$88,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8023444211137.25 ***
	.dword 	$e9835158
	.byte 	$ab,$80
	.byte 	1     ; *** Load Float -195.6 ***
	.dword 	$c3999999
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 41019653431.172035 ***
	.dword 	$98cf63d3
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -859.1 ***
	.dword 	$d6c66666
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -361.41 ***
	.dword 	$b4b47ae1
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 2.073845 ***
	.dword 	$84b9e060
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2188890156390.4165 ***
	.dword 	$fed20296
	.byte 	$a9,$0
	.byte 	1     ; *** Load Float 311076.847616 ***
	.dword 	$97e49b1f
	.byte 	$93,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -159.06 ***
	.dword 	$9f0f5c28
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 2.707423 ***
	.dword 	$ad466b1e
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -161.767423 ***
	.dword 	$a1c475d5
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 667.72 ***
	.dword 	$a6ee147a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 898498911985.9917 ***
	.dword 	$d132b55e
	.byte 	$a8,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 840.34 ***
	.dword 	$d215c28f
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 3.539162874221802e-08 ***
	.dword 	$980181e0
	.byte 	$68,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2.974100129723549e-05 ***
	.dword 	$f97c505f
	.byte 	$71,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16711477230.567425 ***
	.dword 	$f90539fb
	.byte 	$a2,$80
	.byte 	1     ; *** Load Float -931.54 ***
	.dword 	$e8e28f5c
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 15567409499362.777 ***
	.dword 	$e2891e9c
	.byte 	$ac,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.429 ***
	.dword 	$86dd2f1a
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -481.16 ***
	.dword 	$f0947ae1
	.byte 	$89,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.6666666666666665 ***
	.dword 	$eaaaaaaa
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.653181 ***
	.dword 	$9a736deb
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 77.225448 ***
	.dword 	$9a736deb
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 2.774130553007126e-11 ***
	.dword 	$f403dddb
	.byte 	$5d,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.28024 ***
	.dword 	$91ef73c0
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 15.89 ***
	.dword 	$fe3d70a3
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 18.17024 ***
	.dword 	$915ca6ca
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 318.86 ***
	.dword 	$9f6e147a
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -385.83 ***
	.dword 	$c0ea3d70
	.byte 	$89,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 661.2 ***
	.dword 	$a54ccccc
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -90817901235693.16 ***
	.dword 	$a532617c
	.byte 	$af,$80
	.byte 	1     ; *** Load Float -424.15 ***
	.dword 	$d4133333
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -90817901235269.0 ***
	.dword 	$a532617c
	.byte 	$af,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 1.0096442792928428e-14 ***
	.dword 	$b5e19fc2
	.byte 	$52,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -14.00000000000001 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.465203 ***
	.dword 	$877178b3
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 23.465203000000002 ***
	.dword 	$bbb8bc59
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.086459 ***
	.dword 	$8b1116a8
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 3.238345 ***
	.dword 	$cf410b63
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.324804 ***
	.dword 	$8a64cb5b
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -786.27 ***
	.dword 	$c49147ae
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 791.33 ***
	.dword 	$c5d51eb8
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2054441771.466752 ***
	.dword 	$f4e89656
	.byte 	$9f,$80
	.byte 	1     ; *** Load Float -637.8 ***
	.dword 	$9f733333
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3221137.929549627 ***
	.dword 	$c49a47b7
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.133735 ***
	.dword 	$a4478e9f
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -4.434419679455459e-12 ***
	.dword 	$9c05b39e
	.byte 	$5b,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.2765135513109267e-11 ***
	.dword 	$c83e8724
	.byte 	$5d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.384152 ***
	.dword 	$ec4af922
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 7.384152 ***
	.dword 	$ec4af922
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.4 ***
	.dword 	$d9999999
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 755.23 ***
	.dword 	$bcceb851
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.018537399202891835 ***
	.dword 	$97dbbe6a
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 205679394982010.53 ***
	.dword 	$bb107746
	.byte 	$b0,$0
	.byte 	1     ; *** Load Float 7.175101 ***
	.dword 	$e59a6d69
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 28665714250156.273 ***
	.dword 	$d0920db8
	.byte 	$ad,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.276242518448271e-13 ***
	.dword 	$9483558a
	.byte 	$58,$80
	.byte 	1     ; *** Load Float 194.16 ***
	.dword 	$c228f5c2
	.byte 	$88,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.0244352473819162e-10 ***
	.dword 	$e14693d5
	.byte 	$5f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -172.67 ***
	.dword 	$acab851e
	.byte 	$88,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 188.67 ***
	.dword 	$bcab851e
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 35171384107.7289 ***
	.dword 	$83060bb2
	.byte 	$a4,$0
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 35171384093.7289 ***
	.dword 	$83060bb1
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -275.43 ***
	.dword 	$89b70a3d
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 719.49 ***
	.dword 	$b3df5c28
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 444.06 ***
	.dword 	$de07ae14
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.2937739491462706e-08 ***
	.dword 	$de44c7b0
	.byte 	$66,$0
	.byte 	1     ; *** Load Float 158030.364672 ***
	.dword 	$9a539756
	.byte 	$92,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.884608521635528e-16 ***
	.dword 	$e3422467
	.byte 	$4e,$0
	.byte 	1     ; *** Load Float 4.701321 ***
	.dword 	$967138bc
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -4.701320999999999 ***
	.dword 	$967138bc
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8332992468.484097 ***
	.dword 	$f857afea
	.byte 	$a1,$80
	.byte 	1     ; *** Load Float 599.09 ***
	.dword 	$95c5c28f
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -8332993067.574097 ***
	.dword 	$f857b115
	.byte 	$a1,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.662297 ***
	.dword 	$ea6312f4
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 803.54 ***
	.dword 	$c8e28f5c
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -799.877703 ***
	.dword 	$c7f82c49
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.073019 ***
	.dword 	$812b15f8
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 385.25 ***
	.dword 	$c0a00000
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.020955273199221285 ***
	.dword 	$abaa64a2
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.774094 ***
	.dword 	$e315831f
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -88857236.209664 ***
	.dword 	$a97b5286
	.byte 	$9b,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -634.83 ***
	.dword 	$9eb51eb8
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -0.105005 ***
	.dword 	$d70cdc87
	.byte 	$7d,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -634.724995 ***
	.dword 	$9eae6651
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.515227 ***
	.dword 	$c1f2f555
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -237525847681.0076 ***
	.dword 	$dd36933a
	.byte 	$a6,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -6.379208893656573e-12 ***
	.dword 	$e072ce3b
	.byte 	$5b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 41.05 ***
	.dword 	$a4333333
	.byte 	$86,$0
	.byte 	1     ; *** Load Float 1.970907 ***
	.dword 	$fc46ae3a
	.byte 	$81,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 39.079093 ***
	.dword 	$9c50fdc1
	.byte 	$86,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1926766.788608 ***
	.dword 	$eb33764f
	.byte 	$95,$0
	.byte 	1     ; *** Load Float 1.275259 ***
	.dword 	$a33bafd9
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.744575 ***
	.dword 	$9be9c779
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -77.85 ***
	.dword 	$9bb33333
	.byte 	$87,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -68.105425 ***
	.dword 	$8835fa43
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.555966377258301e-09 ***
	.dword 	$afa50939
	.byte 	$64,$0
	.byte 	1     ; *** Load Float -8861239086.153728 ***
	.dword 	$840af1cb
	.byte 	$a2,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 8861239086.153728 ***
	.dword 	$840af1cb
	.byte 	$a2,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -2.2764770507812502e-05 ***
	.dword 	$bef6f8f0
	.byte 	$71,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 702840.3820064453 ***
	.dword 	$ab97861c
	.byte 	$94,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 268.27 ***
	.dword 	$86228f5c
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 14367605.129216 ***
	.dword 	$db3b7521
	.byte 	$98,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 3854397428.014776 ***
	.dword 	$e5bd6ff4
	.byte 	$a0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.9333139061927795e-10 ***
	.dword 	$d491f2dc
	.byte 	$60,$80
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 104.0 ***
	.dword 	$d0000000
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 5.235603 ***
	.dword 	$a78a0f4d
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.959604 ***
	.dword 	$fad44dca
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 4.529694 ***
	.dword 	$90f340d4
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 6.489298 ***
	.dword 	$cfa85447
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -127.07 ***
	.dword 	$fe23d70a
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 363.11 ***
	.dword 	$b58e147a
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 236.04000000000002 ***
	.dword 	$ec0a3d70
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.5929317474365233e-07 ***
	.dword 	$ab0a2ca9
	.byte 	$6a,$80
	.byte 	1     ; *** Load Float 2.670495 ***
	.dword 	$aae963dc
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 2.670494840706825 ***
	.dword 	$aae96331
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -967.34 ***
	.dword 	$f1d5c28f
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -0.00025051611328125 ***
	.dword 	$8357b41b
	.byte 	$75,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.147205 ***
	.dword 	$e4b5e742
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -23207.215104000003 ***
	.dword 	$b54e6e22
	.byte 	$8f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.454804 ***
	.dword 	$e8dc11e4
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float 0.662749 ***
	.dword 	$a9a9eb20
	.byte 	$80,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.20794500000000005 ***
	.dword 	$d4ef88b9
	.byte 	$7e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2431591955059.1797 ***
	.dword 	$8d898b2e
	.byte 	$aa,$80
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -2431591955074.1797 ***
	.dword 	$8d898b2e
	.byte 	$aa,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.975463 ***
	.dword 	$fcdbf8b9
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 284.1 ***
	.dword 	$8e0ccccc
	.byte 	$89,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.006953407250967969 ***
	.dword 	$e3d9685e
	.byte 	$79,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -250.28 ***
	.dword 	$fa47ae14
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -31.285 ***
	.dword 	$fa47ae14
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 154.28 ***
	.dword 	$9a47ae14
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 5.283498 ***
	.dword 	$a9126a65
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 159.563498 ***
	.dword 	$9f904167
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.0 ***
	.dword 	$a0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1.0940141237369971e-14 ***
	.dword 	$c5147f13
	.byte 	$52,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -457032490853107.94 ***
	.dword 	$cfd595a2
	.byte 	$b1,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.398524 ***
	.dword 	$8cc0b567
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.2587367058823529 ***
	.dword 	$84792334
	.byte 	$7f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -340029.07955200004 ***
	.dword 	$a607a28b
	.byte 	$93,$80
	.byte 	1     ; *** Load Float 7013.482496 ***
	.dword 	$db2bdc26
	.byte 	$8d,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2384787997.5689435 ***
	.dword 	$8e24fa1d
	.byte 	$a0,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 55884327749.15686 ***
	.dword 	$d02f72b4
	.byte 	$a4,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 55884327756.15686 ***
	.dword 	$d02f72b4
	.byte 	$a4,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -742.83 ***
	.dword 	$b9b51eb8
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -5.454696655273437e-06 ***
	.dword 	$b7077ccc
	.byte 	$6f,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -836.07 ***
	.dword 	$d1047ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -468.49 ***
	.dword 	$ea3eb851
	.byte 	$89,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1304.56 ***
	.dword 	$a311eb85
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.026717 ***
	.dword 	$80dadd9c
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.460676781396614e-14 ***
	.dword 	$be847b24
	.byte 	$55,$0
	.byte 	1     ; *** Load Float 2.672742027698405e-15 ***
	.dword 	$c097635e
	.byte 	$50,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.556163 ***
	.dword 	$b1cc1659
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.612841 ***
	.dword 	$9ce325d4
	.byte 	$80,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 9.066239040795248 ***
	.dword 	$910f50ab
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -119371567298152.25 ***
	.dword 	$d922b7ba
	.byte 	$af,$80
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 954972538385218.0 ***
	.dword 	$d922b7ba
	.byte 	$b2,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.464208 ***
	.dword 	$bb6b2af1
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -122686.40665599999 ***
	.dword 	$ef9f340d
	.byte 	$91,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.1934557706180831e-05 ***
	.dword 	$c83a88f8
	.byte 	$70,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.384978 ***
	.dword 	$cc51bd61
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 549.71 ***
	.dword 	$896d70a3
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.922896 ***
	.dword 	$dd885d31
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 66459.533312 ***
	.dword 	$81cdc443
	.byte 	$91,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 460092.43732751155 ***
	.dword 	$e0a78dfe
	.byte 	$93,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.926909 ***
	.dword 	$bb527a20
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -708022.632448 ***
	.dword 	$acdb6a1e
	.byte 	$94,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -708019.705539 ***
	.dword 	$acdb3b49
	.byte 	$94,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -612.21 ***
	.dword 	$990d70a3
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -575.54 ***
	.dword 	$8fe28f5c
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1187.75 ***
	.dword 	$94780000
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.047126 ***
	.dword 	$80c10731
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 8.410215 ***
	.dword 	$86903d9a
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.9568276197457496 ***
	.dword 	$f4f2a7a6
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 3524171.661312 ***
	.dword 	$d7192ea5
	.byte 	$96,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 3524151.661312 ***
	.dword 	$d718dea5
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -2.3268512450158598e-14 ***
	.dword 	$d1958969
	.byte 	$53,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.379729 ***
	.dword 	$d84d7add
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -405.31 ***
	.dword 	$caa7ae14
	.byte 	$89,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.008338627223606622 ***
	.dword 	$889ebcce
	.byte 	$7a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.611403 ***
	.dword 	$b3909d06
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 5.611403 ***
	.dword 	$b3909d06
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -132.37 ***
	.dword 	$845eb851
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -149.37 ***
	.dword 	$955eb851
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 261.78 ***
	.dword 	$82e3d70a
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 3.601537 ***
	.dword 	$e67f950b
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.25 ***
	.dword 	$80000000
	.byte 	$7f,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.530128 ***
	.dword 	$b0f6cefe
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 1.136017 ***
	.dword 	$9169014b
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 8.312544 ***
	.dword 	$85002e23
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.045101956753552 ***
	.dword 	$82e2f351
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 110382001.68448001 ***
	.dword 	$d2897635
	.byte 	$9b,$0
	.byte 	1     ; *** Load Float 3.074945 ***
	.dword 	$c4cbe61c
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 110381998.60953501 ***
	.dword 	$d28975d3
	.byte 	$9b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.528817 ***
	.dword 	$e1d82342
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -640.73 ***
	.dword 	$a02eb851
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.005507494576498681 ***
	.dword 	$b478368b
	.byte 	$79,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.214188 ***
	.dword 	$9b6a832b
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 7.214188 ***
	.dword 	$e6daa0ca
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.0 ***
	.dword 	$80000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 905.86 ***
	.dword 	$e2770a3d
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.002207846687126046 ***
	.dword 	$90b18550
	.byte 	$78,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 343.01 ***
	.dword 	$ab8147ae
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 339446727285.1456 ***
	.dword 	$9e113404
	.byte 	$a7,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 339446727628.15564 ***
	.dword 	$9e113407
	.byte 	$a7,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -474.01 ***
	.dword 	$ed0147ae
	.byte 	$89,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3047.40352 ***
	.dword 	$be7674d1
	.byte 	$8c,$0
	.byte 	1     ; *** Load Float 6.524301 ***
	.dword 	$d0c712e4
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 19882.17783293952 ***
	.dword 	$9b545b0c
	.byte 	$8f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2221957.709824 ***
	.dword 	$879e16d6
	.byte 	$96,$0
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.9887165874242783e-10 ***
	.dword 	$a44e7253
	.byte 	$61,$80
	.byte 	1     ; *** Load Float 4.333452 ***
	.dword 	$8aaba387
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.2951459873206914e-09 ***
	.dword 	$b200e5f8
	.byte 	$63,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 428.19 ***
	.dword 	$d61851eb
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 414.19 ***
	.dword 	$cf1851eb
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.519281005859375e-05 ***
	.dword 	$d35525cc
	.byte 	$71,$0
	.byte 	1     ; *** Load Float -4673.568768 ***
	.dword 	$920c8cd6
	.byte 	$8d,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -5.39048665146201e-09 ***
	.dword 	$b93738d6
	.byte 	$65,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 88831.295488 ***
	.dword 	$ad7fa5d2
	.byte 	$91,$0
	.byte 	1     ; *** Load Float 3.728155 ***
	.dword 	$ee9a176d
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.53938 ***
	.dword 	$8a14cec4
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.03852714285714286 ***
	.dword 	$9dcea329
	.byte 	$7c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 191247328501125.1 ***
	.dword 	$adf03d14
	.byte 	$b0,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3824946570022502.0 ***
	.dword 	$d96c4c59
	.byte 	$b4,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 300.1 ***
	.dword 	$960ccccc
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 899531.4073600001 ***
	.dword 	$db9cb684
	.byte 	$94,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -899231.3073600001 ***
	.dword 	$db89f4ea
	.byte 	$94,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.205057144165038e-08 ***
	.dword 	$9aba3875
	.byte 	$69,$0
	.byte 	1     ; *** Load Float 2.181345224380493e-08 ***
	.dword 	$bb6049ec
	.byte 	$67,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.3030338635239596 ***
	.dword 	$d364e825
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.45067024230957e-07 ***
	.dword 	$e2d8904f
	.byte 	$6c,$0
	.byte 	1     ; *** Load Float 2.742931246757507e-08 ***
	.dword 	$eb9db22d
	.byte 	$67,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 8.72496336698532e-07 ***
	.dword 	$ea357de0
	.byte 	$6c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.303024 ***
	.dword 	$9b25f633
	.byte 	$7f,$0
	.byte 	1     ; *** Load Float 5.166918 ***
	.dword 	$a557646a
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 5.469942 ***
	.dword 	$af09c3ce
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.491663 ***
	.dword 	$fbbb40b3
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -0.491663 ***
	.dword 	$fbbb40b3
	.byte 	$7f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.4188275933265686e-10 ***
	.dword 	$f2ed783d
	.byte 	$61,$0
	.byte 	1     ; *** Load Float 5.770063 ***
	.dword 	$b8a45b29
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 5.770063000441883 ***
	.dword 	$b8a45b29
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 910.81 ***
	.dword 	$e3b3d70a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 913.81 ***
	.dword 	$e473d70a
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
