; Using seed 82766
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
	.byte 	1     ; *** Load Float 4.415993 ***
	.dword 	$8d4fd08d
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 70.655888 ***
	.dword 	$8d4fd08d
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 3.677453 ***
	.dword 	$eb5b63d3
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.677453 ***
	.dword 	$95adb1e9
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -238.85 ***
	.dword 	$eed99999
	.byte 	$88,$80
	.byte 	1     ; *** Load Float 5.805235 ***
	.dword 	$b9c47c30
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -244.655235 ***
	.dword 	$f4a7bd7b
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 20.0 ***
	.dword 	$a0000000
	.byte 	$85,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 510996929497.2682 ***
	.dword 	$edf394b7
	.byte 	$a7,$0
	.byte 	1     ; *** Load Float 931.97 ***
	.dword 	$e8fe147a
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 548297616.3366505 ***
	.dword 	$82b96e41
	.byte 	$9e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -17.0 ***
	.dword 	$88000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.609307 ***
	.dword 	$937f7164
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -9.0 ***
	.dword 	$90000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 13.609307000000001 ***
	.dword 	$d9bfb8b2
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -26.88 ***
	.dword 	$d70a3d70
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -16.0 ***
	.dword 	$80000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -42.879999999999995 ***
	.dword 	$ab851eb8
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -13.0 ***
	.dword 	$d0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 61126645.645312 ***
	.dword 	$e92dfd69
	.byte 	$9a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 61126632.645312 ***
	.dword 	$e92dfa29
	.byte 	$9a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.0002573525390625 ***
	.dword 	$86ed45e9
	.byte 	$75,$80
	.byte 	1     ; *** Load Float -119.08 ***
	.dword 	$ee28f5c2
	.byte 	$87,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -119.08025735253906 ***
	.dword 	$ee29177d
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20.0 ***
	.dword 	$a0000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -7.417014558086521e-15 ***
	.dword 	$859cf13c
	.byte 	$52,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -941.58 ***
	.dword 	$eb651eb8
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -999.07 ***
	.dword 	$f9c47ae1
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.9424564845306135 ***
	.dword 	$f144d402
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2660.405248 ***
	.dword 	$a6467be5
	.byte 	$8c,$80
	.byte 	1     ; *** Load Float -127942.393856 ***
	.dword 	$f9e33269
	.byte 	$91,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 125281.988608 ***
	.dword 	$f4b0fe8a
	.byte 	$91,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.802423 ***
	.dword 	$99ad72ff
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -168.3 ***
	.dword 	$a84ccccc
	.byte 	$88,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -808.2477909 ***
	.dword 	$ca0fdbce
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -100513240.58009599 ***
	.dword 	$bfb6bb12
	.byte 	$9b,$80
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -319.38 ***
	.dword 	$9fb0a3d7
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 19.0 ***
	.dword 	$98000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -6068.22 ***
	.dword 	$bda1c28f
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.798447 ***
	.dword 	$e63382e4
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 4.0446252569381614e-14 ***
	.dword 	$b6275ab7
	.byte 	$54,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9605597463041.803 ***
	.dword 	$8bc7a398
	.byte 	$ac,$0
	.byte 	1     ; *** Load Float 789.39 ***
	.dword 	$c558f5c2
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 7582562581350569.0 ***
	.dword 	$d7826769
	.byte 	$b5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.66 ***
	.dword 	$aa3d70a3
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 9.002746 ***
	.dword 	$900b3f63
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 23.94730436 ***
	.dword 	$bf94144e
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.925129 ***
	.dword 	$ecd5410f
	.byte 	$80,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 15.133024691691645 ***
	.dword 	$f220de7f
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 32484179.836928003 ***
	.dword 	$f7d5a9eb
	.byte 	$99,$0
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2953107.257902546 ***
	.dword 	$b43e4d08
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 12.0 ***
	.dword 	$c0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.1154622825415572e-13 ***
	.dword 	$fb2e05cc
	.byte 	$55,$0
	.byte 	1     ; *** Load Float 4.239418 ***
	.dword 	$87a94ff0
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 4.728910878927763e-13 ***
	.dword 	$851b64df
	.byte 	$58,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 48408.428543999995 ***
	.dword 	$bd186db5
	.byte 	$90,$0
	.byte 	1     ; *** Load Float 9.091815 ***
	.dword 	$91781301
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 48417.520358999995 ***
	.dword 	$bd218536
	.byte 	$90,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	1     ; *** Load Float -902.83 ***
	.dword 	$e1b51eb8
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -775.67 ***
	.dword 	$c1eae147
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -774.67 ***
	.dword 	$c1aae147
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.081287 ***
	.dword 	$e299e731
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 910.28 ***
	.dword 	$e391eb85
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 6445.9539303599995 ***
	.dword 	$c96fa1a6
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.315554 ***
	.dword 	$a1904b3c
	.byte 	$7f,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 7.684446 ***
	.dword 	$f5e6fb4c
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 818.21 ***
	.dword 	$cc8d70a3
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 804.21 ***
	.dword 	$c90d70a3
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.4774541854858397e-09 ***
	.dword 	$eef8055f
	.byte 	$64,$80
	.byte 	1     ; *** Load Float 7.569149602204561e-11 ***
	.dword 	$a672862f
	.byte 	$5f,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2.6321370964754733e-19 ***
	.dword 	$9b5fbb30
	.byte 	$43,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -836.57 ***
	.dword 	$d1247ae1
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 6.239218 ***
	.dword 	$c7a7ac81
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -566.14 ***
	.dword 	$8d88f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 3.493985 ***
	.dword 	$df9d7342
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.330728 ***
	.dword 	$8a9552e2
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 4.330728 ***
	.dword 	$8a9552e2
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 485.71 ***
	.dword 	$f2dae147
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 6.423105 ***
	.dword 	$cd8a137f
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.363987394142896e-13 ***
	.dword 	$9992428d
	.byte 	$56,$80
	.byte 	1     ; *** Load Float 136115029.80300802 ***
	.dword 	$81cf355c
	.byte 	$9c,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -136115029.80300802 ***
	.dword 	$81cf355c
	.byte 	$9c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.866527 ***
	.dword 	$ddd4b6a6
	.byte 	$80,$80
	.byte 	1     ; *** Load Float 163.5 ***
	.dword 	$a3800000
	.byte 	$88,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -164.366527 ***
	.dword 	$a45dd4b6
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 528.61 ***
	.dword 	$84270a3d
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.02459279998486597 ***
	.dword 	$c976d6f4
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.44489 ***
	.dword 	$8e3c89f4
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 742.96 ***
	.dword 	$b9bd70a3
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -738.51511 ***
	.dword 	$b8a0f78f
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -497.63 ***
	.dword 	$f8d0a3d7
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 1.464952 ***
	.dword 	$bb838c11
	.byte 	$81,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -689.39 ***
	.dword 	$ac58f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 7.106155 ***
	.dword 	$e3659f2b
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -93.16 ***
	.dword 	$ba51eb85
	.byte 	$87,$80
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 186.32 ***
	.dword 	$ba51eb85
	.byte 	$88,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.099762 ***
	.dword 	$9198a009
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -707.21 ***
	.dword 	$b0cd70a3
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 723.21 ***
	.dword 	$b4cd70a3
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.006129 ***
	.dword 	$80c8d5c7
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 2.776331 ***
	.dword 	$b1af6837
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -368637.37856 ***
	.dword 	$b3ffac1d
	.byte 	$93,$80
	.byte 	1     ; *** Load Float -108585844213.80914 ***
	.dword 	$ca41c3ef
	.byte 	$a5,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 108585475576.43059 ***
	.dword 	$ca4196ef
	.byte 	$a5,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.43702 ***
	.dword 	$dfc115df
	.byte 	$7f,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 18.305798361631044 ***
	.dword 	$92724669
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 643.8 ***
	.dword 	$a0f33333
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -4.377609002403915e-12 ***
	.dword 	$9a05ff1d
	.byte 	$5b,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 643.8000000000044 ***
	.dword 	$a0f33333
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.616815 ***
	.dword 	$b3bcf2cf
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 3.712213 ***
	.dword 	$ed94e5d5
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 20.850813661595 ***
	.dword 	$a6ce7764
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -554.38 ***
	.dword 	$8a9851eb
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -554.38 ***
	.dword 	$8a9851eb
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -852584.562688 ***
	.dword 	$d0268900
	.byte 	$94,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -14493937.565696001 ***
	.dword 	$dd28f190
	.byte 	$98,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -880.98 ***
	.dword 	$dc3eb851
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 2.869422 ***
	.dword 	$b7a49c2c
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -307.0235050822082 ***
	.dword 	$99830236
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 318.93 ***
	.dword 	$9f770a3d
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 3.245478 ***
	.dword 	$cfb5e95b
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1035.08029854 ***
	.dword 	$816291ce
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.725579833984375e-05 ***
	.dword 	$9c431bde
	.byte 	$72,$0
	.byte 	1     ; *** Load Float 721.87 ***
	.dword 	$b477ae14
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.156695556640625e-05 ***
	.dword 	$8466c2ac
	.byte 	$72,$0
	.byte 	1     ; *** Load Float 0.859341 ***
	.dword 	$dbfdc593
	.byte 	$80,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 934.28 ***
	.dword 	$e991eb85
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -292.71 ***
	.dword 	$925ae147
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 1226.99 ***
	.dword 	$995fae14
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 922.1 ***
	.dword 	$e6866666
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 11987.300000000001 ***
	.dword 	$bb4d3333
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.272021 ***
	.dword 	$88b46562
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -2.1360105 ***
	.dword 	$88b46562
	.byte 	$82,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 268.31 ***
	.dword 	$8627ae14
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 269402360.512512 ***
	.dword 	$807607c4
	.byte 	$9d,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 9.959452452070803e-07 ***
	.dword 	$85ac6b05
	.byte 	$6d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -81.73 ***
	.dword 	$a375c28f
	.byte 	$87,$80
	.byte 	1     ; *** Load Float 2.760014 ***
	.dword 	$b0a411c2
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -29.612168633927222 ***
	.dword 	$ece5b8ab
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -715.39 ***
	.dword 	$b2d8f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -572.4 ***
	.dword 	$8f199999
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -59.89 ***
	.dword 	$ef8f5c28
	.byte 	$86,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -632.29 ***
	.dword 	$9e128f5c
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 799.89 ***
	.dword 	$c7f8f5c2
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 14398.02 ***
	.dword 	$e0f8147a
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -768.06 ***
	.dword 	$c003d70a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 5.504911 ***
	.dword 	$b0283b1d
	.byte 	$83,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -762.555089 ***
	.dword 	$bea38694
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 13.0 ***
	.dword 	$d0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -6607273234561.761 ***
	.dword 	$c04c0592
	.byte 	$ab,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.967528742719272e-12 ***
	.dword 	$8a73d8cb
	.byte 	$5a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.889292 ***
	.dword 	$fc75147f
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -1.401950555646181e-15 ***
	.dword 	$ca0ad8a1
	.byte 	$4f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 7.889292000000002 ***
	.dword 	$fc75147f
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -618.5 ***
	.dword 	$9aa00000
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -618.5 ***
	.dword 	$9aa00000
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.102458953857422e-07 ***
	.dword 	$dc3fc43b
	.byte 	$6b,$80
	.byte 	1     ; *** Load Float -6.25574259061068e-16 ***
	.dword 	$b44f3ba7
	.byte 	$4e,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -4.1024589601131647e-07 ***
	.dword 	$dc3fc440
	.byte 	$6b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.372281 ***
	.dword 	$be9b9d7f
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float 8.0 ***
	.dword 	$80000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 7.627719 ***
	.dword 	$f4164628
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.672675 ***
	.dword 	$9ac346dc
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -284.77 ***
	.dword 	$8e628f5c
	.byte 	$89,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.03396662218632581 ***
	.dword 	$8b2095b7
	.byte 	$7c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.209142 ***
	.dword 	$cd629520
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -191.46 ***
	.dword 	$bf75c28f
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.01676142275148856 ***
	.dword 	$894f4051
	.byte 	$7b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.730247 ***
	.dword 	$aebc5de9
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -8.190741 ***
	.dword 	$830d466f
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 546.18 ***
	.dword 	$888b851e
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.02013988062543484 ***
	.dword 	$a4fc6414
	.byte 	$7b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -404.47 ***
	.dword 	$ca3c28f5
	.byte 	$89,$80
	.byte 	1     ; *** Load Float 13333909451434.885 ***
	.dword 	$c208aefb
	.byte 	$ac,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -13333909451839.355 ***
	.dword 	$c208aefb
	.byte 	$ac,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 87.78 ***
	.dword 	$af8f5c28
	.byte 	$87,$0
	.byte 	1     ; *** Load Float -720.3 ***
	.dword 	$b4133333
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -63227.933999999994 ***
	.dword 	$f6fbef1a
	.byte 	$90,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 15.0 ***
	.dword 	$f0000000
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.4166666666666667 ***
	.dword 	$d5555555
	.byte 	$7f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.007176 ***
	.dword 	$80759253
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 2.007176 ***
	.dword 	$80759253
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.014352 ***
	.dword 	$80759253
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -4.9085571163232084e-15 ***
	.dword 	$b0d972cd
	.byte 	$51,$80
	.byte 	1     ; *** Load Float -612.78 ***
	.dword 	$9931eb85
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 8.010308946641875e-18 ***
	.dword 	$93c39d4f
	.byte 	$48,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -698.22 ***
	.dword 	$ae8e147a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 979.94 ***
	.dword 	$f4fc28f5
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.7125130110006735 ***
	.dword 	$b66740b0
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.553172 ***
	.dword 	$98d9cae2
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 7.0 ***
	.dword 	$e0000000
	.byte 	$83,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.3647388571428571 ***
	.dword 	$aeafc34b
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float -711.28 ***
	.dword 	$b1d1eb85
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 523788098019.0003 ***
	.dword 	$f3e86833
	.byte 	$a7,$0
	.byte 	1     ; *** Load Float 16.0 ***
	.dword 	$80000000
	.byte 	$85,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 523788098003.0003 ***
	.dword 	$f3e86833
	.byte 	$a7,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 653.04 ***
	.dword 	$a3428f5c
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 642.04 ***
	.dword 	$a0828f5c
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.670495 ***
	.dword 	$d574b1ee
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -500624638178131.7 ***
	.dword 	$e3a860dc
	.byte 	$b1,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -1.3324344211813466e-14 ***
	.dword 	$f007b120
	.byte 	$52,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.271159 ***
	.dword 	$88ad55a3
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 0.577308 ***
	.dword 	$93ca7503
	.byte 	$80,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 4.848467 ***
	.dword 	$9b26a444
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.478156 ***
	.dword 	$f4d0dcfc
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -5.0 ***
	.dword 	$a0000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 4.521844 ***
	.dword 	$90b2f230
	.byte 	$83,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 431.33 ***
	.dword 	$d7aa3d70
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -814.97 ***
	.dword 	$cbbe147a
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -383.64000000000004 ***
	.dword 	$bfd1eb85
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.254398375749588e-09 ***
	.dword 	$ac67381d
	.byte 	$63,$0
	.byte 	1     ; *** Load Float -9.22991943359375e-06 ***
	.dword 	$9ada33bd
	.byte 	$70,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.9421463012695313e-07 ***
	.dword 	$d3a4723a
	.byte 	$6b,$0
	.byte 	1     ; *** Load Float 6.318396 ***
	.dword 	$ca304cce
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2.49080414213562e-06 ***
	.dword 	$a727b077
	.byte 	$6e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -19.0 ***
	.dword 	$98000000
	.byte 	$85,$80
	.byte 	1     ; *** Load Float -7.0 ***
	.dword 	$e0000000
	.byte 	$83,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 2.7142857142857144 ***
	.dword 	$adb6db6d
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -883.37 ***
	.dword 	$dcd7ae14
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 513.15 ***
	.dword 	$80499999
	.byte 	$8a,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0 ***
	.dword 	$80000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float 951.24 ***
	.dword 	$edcf5c28
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.002102518817543417 ***
	.dword 	$89ca698f
	.byte 	$78,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -232592906355176.62 ***
	.dword 	$d38ac18f
	.byte 	$b0,$80
	.byte 	1     ; *** Load Float -232592906355176.62 ***
	.dword 	$d38ac18f
	.byte 	$b0,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 5.409946008674796e+28 ***
	.dword 	$aece0647
	.byte 	$e0,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 198.46 ***
	.dword 	$c675c28f
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 428.8 ***
	.dword 	$d6666666
	.byte 	$89,$0
	.byte 	1     ; *** Load Float -47.18 ***
	.dword 	$bcb851eb
	.byte 	$86,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 475.98 ***
	.dword 	$edfd70a3
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 3.632861 ***
	.dword 	$e880cb6c
	.byte 	$82,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 816.76 ***
	.dword 	$cc30a3d7
	.byte 	$8a,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -816.76 ***
	.dword 	$cc30a3d7
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -603.51 ***
	.dword 	$96e0a3d7
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 4.453697 ***
	.dword 	$8e84af92
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -2687.85067647 ***
	.dword 	$a7fd9c5e
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 510.59 ***
	.dword 	$ff4b851e
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 173489916645379.94 ***
	.dword 	$9dc9c4da
	.byte 	$b0,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -173489916644869.34 ***
	.dword 	$9dc9c4da
	.byte 	$b0,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -20040832799.21152 ***
	.dword 	$9550dae3
	.byte 	$a3,$80
	.byte 	1     ; *** Load Float 396.79 ***
	.dword 	$c6651eb8
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -20040833196.001522 ***
	.dword 	$9550db15
	.byte 	$a3,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 957.72 ***
	.dword 	$ef6e147a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -18.0 ***
	.dword 	$90000000
	.byte 	$85,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 939.72 ***
	.dword 	$eaee147a
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.5347191012770056e-16 ***
	.dword 	$921dda05
	.byte 	$4d,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -2.5347191012770056e-16 ***
	.dword 	$921dda05
	.byte 	$4d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -32.74 ***
	.dword 	$82f5c28f
	.byte 	$86,$80
	.byte 	1     ; *** Load Float 103239391957934.4 ***
	.dword 	$bbca9691
	.byte 	$af,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -3380057692702772.5 ***
	.dword 	$c0225021
	.byte 	$b4,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.19322 ***
	.dword 	$cc5db76b
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 2.859543 ***
	.dword 	$b702c0a4
	.byte 	$82,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.850279 ***
	.dword 	$9d9abe27
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 9.664233398437501e-05 ***
	.dword 	$caac753e
	.byte 	$73,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2.0083999633789063e-07 ***
	.dword 	$d7a67a52
	.byte 	$6a,$80
	.byte 	1     ; *** Load Float 3.303697 ***
	.dword 	$d36fc58a
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 3.303696799160004 ***
	.dword 	$d36fc4b3
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 816.56 ***
	.dword 	$cc23d70a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 816.56 ***
	.dword 	$cc23d70a
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.2241852283477785e-09 ***
	.dword 	$d5dc8323
	.byte 	$65,$80
	.byte 	1     ; *** Load Float 126.6 ***
	.dword 	$fd333333
	.byte 	$87,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -7.879818499088287e-07 ***
	.dword 	$d385b34d
	.byte 	$6c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.275309 ***
	.dword 	$a33d5347
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 6.98118 ***
	.dword 	$df65d399
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.665537 ***
	.dword 	$954c1440
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 307.94 ***
	.dword 	$99f851eb
	.byte 	$89,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 312.60553699999997 ***
	.dword 	$9c4d823c
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 2.435632050037384e-09 ***
	.dword 	$a7601797
	.byte 	$64,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7.282076 ***
	.dword 	$e906c43f
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 45927024.820224 ***
	.dword 	$af329c34
	.byte 	$9a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 45927032.1023 ***
	.dword 	$af329e06
	.byte 	$9a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.5709126677829773e-12 ***
	.dword 	$fb47d805
	.byte 	$5a,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 3.000000000003571 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float 1.162959 ***
	.dword 	$94dbd72b
	.byte 	$81,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1.162959 ***
	.dword 	$94dbd72b
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.058456420898437e-08 ***
	.dword 	$ae4f3343
	.byte 	$68,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 4.0584564208984375e-09 ***
	.dword 	$8b728f69
	.byte 	$65,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.844294 ***
	.dword 	$d823a6ce
	.byte 	$80,$80
	.byte 	1     ; *** Load Float -13210666567.467007 ***
	.dword 	$c4dab191
	.byte 	$a2,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -13210666568.3113 ***
	.dword 	$c4dab192
	.byte 	$a2,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 277.772288 ***
	.dword 	$8ae2da55
	.byte 	$89,$0
	.byte 	1     ; *** Load Float 8.850017 ***
	.dword 	$8d99ab6d
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2458.2894709288958 ***
	.dword 	$99a4a1ac
	.byte 	$8c,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 32882.556928 ***
	.dword 	$80728e92
	.byte 	$90,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.6605911254882812e-06 ***
	.dword 	$dee17a02
	.byte 	$6d,$80
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.1861365182059151e-07 ***
	.dword 	$feb88b71
	.byte 	$69,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 526.29 ***
	.dword 	$83928f5c
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 17.0 ***
	.dword 	$88000000
	.byte 	$85,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7001367.117823999 ***
	.dword 	$d5aa2e3c
	.byte 	$97,$0
	.byte 	1     ; *** Load Float -673.93 ***
	.dword 	$a87b851e
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -99338264229.44563 ***
	.dword 	$b9082cf5
	.byte 	$a5,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -99338264215.44563 ***
	.dword 	$b9082cf4
	.byte 	$a5,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -338.94 ***
	.dword 	$a97851eb
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 338.94 ***
	.dword 	$a97851eb
	.byte 	$89,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.0 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	1     ; *** Load Float -862.75 ***
	.dword 	$d7b00000
	.byte 	$8a,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.0011590843233845263 ***
	.dword 	$97ec6a86
	.byte 	$77,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.037322 ***
	.dword 	$8131bde8
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -11.0 ***
	.dword 	$b0000000
	.byte 	$84,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 15.037322 ***
	.dword 	$f098def4
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.694169 ***
	.dword 	$8b1b50f4
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 534.96 ***
	.dword 	$85bd70a3
	.byte 	$8a,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.01625199828024525 ***
	.dword 	$8522e923
	.byte 	$7b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -402.37 ***
	.dword 	$c92f5c28
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -336.06 ***
	.dword 	$a807ae14
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -66.31 ***
	.dword 	$849eb851
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.1243962692096828e-11 ***
	.dword 	$badd26b7
	.byte 	$5d,$0
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2.974154776893556e-10 ***
	.dword 	$a38181e0
	.byte 	$61,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 11.0 ***
	.dword 	$b0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 3.499819 ***
	.dword 	$dffd08d4
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 3.143019681874977 ***
	.dword 	$c9273c06
	.byte 	$82,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 8.195801 ***
	.dword 	$8322003a
	.byte 	$84,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -65.566408 ***
	.dword 	$8322003a
	.byte 	$87,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float 0.577841 ***
	.dword 	$93ed6345
	.byte 	$80,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -11.422159 ***
	.dword 	$b6c129cb
	.byte 	$84,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -740.22 ***
	.dword 	$b90e147a
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -4.0 ***
	.dword 	$80000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -736.22 ***
	.dword 	$b80e147a
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 618.29 ***
	.dword 	$9a928f5c
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 624.29 ***
	.dword 	$9c128f5c
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.701061359606683e-13 ***
	.dword 	$d059ea57
	.byte 	$57,$0
	.byte 	1     ; *** Load Float -0.124902 ***
	.dword 	$ffcc9ea9
	.byte 	$7d,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.1249020000003701 ***
	.dword 	$ffcc9ea9
	.byte 	$7d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.089628 ***
	.dword 	$b78ee286
	.byte 	$7d,$0
	.byte 	1     ; *** Load Float -545.75 ***
	.dword 	$88700000
	.byte 	$8a,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.9697136950708235e-15 ***
	.dword 	$fb1c432c
	.byte 	$51,$80
	.byte 	1     ; *** Load Float 6.129794 ***
	.dword 	$c42745bf
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.220805 ***
	.dword 	$83886ad2
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -5.779195 ***
	.dword 	$b8ef2a5a
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 793.98 ***
	.dword 	$c67eb851
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 8.978698 ***
	.dword 	$8fa8bf3b
	.byte 	$84,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 104010.350592 ***
	.dword 	$cb252ce0
	.byte 	$91,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 7502829.715456 ***
	.dword 	$e4f7db6e
	.byte 	$97,$0
	.byte 	1     ; *** Load Float 7502829.715456 ***
	.dword 	$e4f7db6e
	.byte 	$97,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 56292453739129.555 ***
	.dword 	$ccca6ed5
	.byte 	$ae,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -83.21 ***
	.dword 	$a66b851e
	.byte 	$87,$80
	.byte 	1     ; *** Load Float -195.13 ***
	.dword 	$c32147ae
	.byte 	$88,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -278.34 ***
	.dword 	$8b2b851e
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -787.51 ***
	.dword 	$c4e0a3d7
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 2.819726 ***
	.dword 	$b476640a
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -790.3297259999999 ***
	.dword 	$c5951a3b
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -14970809586309.66 ***
	.dword 	$d9da9c99
	.byte 	$ac,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float -0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.010872 ***
	.dword 	$80b22079
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -872.92 ***
	.dword 	$da3ae147
	.byte 	$8a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1755.3303862399998 ***
	.dword 	$db6a9286
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.0 ***
	.dword 	$90000000
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 21304418774764.484 ***
	.dword 	$9b029281
	.byte 	$ad,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 867.66 ***
	.dword 	$d8ea3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 250881924.66124803 ***
	.dword 	$ef42784a
	.byte 	$9c,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 217680210751.57846 ***
	.dword 	$cabb01ac
	.byte 	$a6,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 101.56 ***
	.dword 	$cb1eb851
	.byte 	$87,$0
	.byte 	1     ; *** Load Float 8.110661 ***
	.dword 	$81c54477
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 93.44933900000001 ***
	.dword 	$bae60fc2
	.byte 	$87,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3258.023936 ***
	.dword 	$cba0620a
	.byte 	$8c,$80
	.byte 	1     ; *** Load Float -0.771385 ***
	.dword 	$c5797cc3
	.byte 	$80,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 557.125632 ***
	.dword 	$8b480a5a
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -279.95 ***
	.dword 	$8bf99999
	.byte 	$89,$80
	.byte 	1     ; *** Load Float -907.31 ***
	.dword 	$e2d3d70a
	.byte 	$8a,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1187.26 ***
	.dword 	$946851eb
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -3.4319600672461094e-12 ***
	.dword 	$f180b242
	.byte 	$5a,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 5.147940100869164e-11 ***
	.dword 	$e268a71d
	.byte 	$5e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.798237 ***
	.dword 	$998b2852
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 1.7982370000000003 ***
	.dword 	$e62ca148
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.894483 ***
	.dword 	$9e4fcd67
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 820.47 ***
	.dword 	$cd1e147a
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 8118.12646701 ***
	.dword 	$fdb10301
	.byte 	$8d,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -15.0 ***
	.dword 	$f0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -14.0 ***
	.dword 	$e0000000
	.byte 	$84,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -29.0 ***
	.dword 	$e8000000
	.byte 	$85,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.3063042792491617e-13 ***
	.dword 	$ba20ddc6
	.byte 	$57,$0
	.byte 	1     ; *** Load Float -1185216360137.8838 ***
	.dword 	$89fa3337
	.byte 	$a9,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -1185216360137.8838 ***
	.dword 	$89fa3337
	.byte 	$a9,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 9.252632 ***
	.dword 	$940ac7da
	.byte 	$84,$0
	.byte 	1     ; *** Load Float 0.0001487021484375 ***
	.dword 	$9becedd4
	.byte 	$74,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 9.252780702148439 ***
	.dword 	$940b63c7
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2364371.1078399997 ***
	.dword 	$904f4c6e
	.byte 	$96,$0
	.byte 	1     ; *** Load Float -12732239096529.812 ***
	.dword 	$b947496a
	.byte 	$ac,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 883.11 ***
	.dword 	$dcc70a3d
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -854904806464859.1 ***
	.dword 	$c2620253
	.byte 	$b2,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 854904806465742.2 ***
	.dword 	$c2620253
	.byte 	$b2,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -223370378743252.0 ***
	.dword 	$cb277814
	.byte 	$b0,$80
	.byte 	1     ; *** Load Float -493.13 ***
	.dword 	$f690a3d7
	.byte 	$89,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -223370378742758.88 ***
	.dword 	$cb277814
	.byte 	$b0,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 563.82 ***
	.dword 	$8cf47ae1
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 566.82 ***
	.dword 	$8db47ae1
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 5.969492 ***
	.dword 	$bf061416
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -3887596038885.7363 ***
	.dword 	$e249b1fa
	.byte 	$aa,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 3887596038891.706 ***
	.dword 	$e249b1fa
	.byte 	$aa,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 1.512259 ***
	.dword 	$c191b3f2
	.byte 	$81,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -1.512259 ***
	.dword 	$c191b3f2
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -552.14 ***
	.dword 	$8a08f5c2
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 282.77 ***
	.dword 	$8d628f5c
	.byte 	$89,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -834.91 ***
	.dword 	$d0ba3d70
	.byte 	$8a,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float 241.08 ***
	.dword 	$f1147ae1
	.byte 	$88,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -241.08 ***
	.dword 	$f1147ae1
	.byte 	$88,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 880.41 ***
	.dword 	$dc1a3d70
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float 3.0 ***
	.dword 	$c0000000
	.byte 	$82,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 877.41 ***
	.dword 	$db5a3d70
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 1.53205 ***
	.dword 	$c41a36e2
	.byte 	$81,$0
	.byte 	1     ; *** Load Float 1.94333 ***
	.dword 	$f8bf0995
	.byte 	$81,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 0.788363273350383 ***
	.dword 	$c9d22cec
	.byte 	$80,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.384709 ***
	.dword 	$c4f893fa
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 1 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.773696270556684e-15 ***
	.dword 	$f40c521d
	.byte 	$51,$0
	.byte 	1     ; *** Load Float 0.117534 ***
	.dword 	$f0b5aa71
	.byte 	$7d,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float -1 ***
	.dword 	$80000000
	.byte 	$81,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -844.99 ***
	.dword 	$d33f5c28
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float -2.6785954833030703e-09 ***
	.dword 	$b812599e
	.byte 	$64,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 2.2633863974362612e-06 ***
	.dword 	$97e4aea6
	.byte 	$6e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -7.201742846518754e-14 ***
	.dword 	$a22b3892
	.byte 	$55,$80
	.byte 	1     ; *** Load Float -521.51 ***
	.dword 	$8260a3d7
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 521.5099999999999 ***
	.dword 	$8260a3d7
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.967956 ***
	.dword 	$def97edc
	.byte 	$83,$0
	.byte 	1     ; *** Load Float -248.26 ***
	.dword 	$f8428f5c
	.byte 	$88,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -1729.86475656 ***
	.dword 	$d83bac15
	.byte 	$8b,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 6.0 ***
	.dword 	$c0000000
	.byte 	$83,$0
	.byte 	$7e   ; *** Command ~ ***
	.byte 	1     ; *** Load Float 0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 19.46 ***
	.dword 	$9bae147a
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 578.21 ***
	.dword 	$908d70a3
	.byte 	$8a,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 11251.966600000002 ***
	.dword 	$afcfddcc
	.byte 	$8e,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -195.14 ***
	.dword 	$c323d70a
	.byte 	$88,$80
	.byte 	1     ; *** Load Float -195.14 ***
	.dword 	$c323d70a
	.byte 	$88,$80
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.2693848222843372e-13 ***
	.dword 	$ff829068
	.byte 	$56,$0
	.byte 	1     ; *** Load Float 10.0 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 10.000000000000227 ***
	.dword 	$a0000000
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2569669.705728 ***
	.dword 	$9cd716d2
	.byte 	$96,$0
	.byte 	1     ; *** Load Float 8.313986 ***
	.dword 	$8506162f
	.byte 	$84,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 2569661.391742 ***
	.dword 	$9cd6f591
	.byte 	$96,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -2843.9511039999998 ***
	.dword 	$b1bf37b8
	.byte 	$8c,$80
	.byte 	1     ; *** Load Float 5.985574722290039e-07 ***
	.dword 	$a0ac8e68
	.byte 	$6c,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -2843.951103401442 ***
	.dword 	$b1bf37b8
	.byte 	$8c,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -0.444328 ***
	.dword 	$e37ef5a9
	.byte 	$7f,$80
	.byte 	1     ; *** Load Float 769.78 ***
	.dword 	$c071eb85
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 769.3356719999999 ***
	.dword 	$c0557ba6
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	1     ; *** Load Float -0.763581 ***
	.dword 	$c37a0b5e
	.byte 	$80,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -0.763581 ***
	.dword 	$c37a0b5e
	.byte 	$80,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -723.4 ***
	.dword 	$b4d99999
	.byte 	$8a,$80
	.byte 	1     ; *** Load Float 6.839895 ***
	.dword 	$dae06b7a
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -4947.9800430000005 ***
	.dword 	$9a9fd720
	.byte 	$8d,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.021372 ***
	.dword 	$815e28aa
	.byte 	$82,$0
	.byte 	1     ; *** Load Float -447.4 ***
	.dword 	$dfb33333
	.byte 	$89,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -445.378628 ***
	.dword 	$deb076e1
	.byte 	$89,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 18.0 ***
	.dword 	$90000000
	.byte 	$85,$0
	.byte 	1     ; *** Load Float 4.675879 ***
	.dword 	$95a0ccff
	.byte 	$83,$0
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 13.324121 ***
	.dword 	$d52f9980
	.byte 	$84,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.632672501727939e-11 ***
	.dword 	$8f9c842f
	.byte 	$5d,$80
	.byte 	1     ; *** Load Float -0.351813 ***
	.dword 	$b420d562
	.byte 	$7f,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.35181299998367327 ***
	.dword 	$b420d562
	.byte 	$7f,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 809.51 ***
	.dword 	$ca60a3d7
	.byte 	$8a,$0
	.byte 	1     ; *** Load Float -12.0 ***
	.dword 	$c0000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float -9714.119999999999 ***
	.dword 	$97c87ae1
	.byte 	$8e,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 3.736606 ***
	.dword 	$ef248d7e
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 14.0 ***
	.dword 	$e0000000
	.byte 	$84,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 17.736606000000002 ***
	.dword 	$8de491af
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 8.462524 ***
	.dword 	$87667f90
	.byte 	$84,$0
	.byte 	1     ; *** Load Float -607.85 ***
	.dword 	$97f66666
	.byte 	$8a,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 616.312524 ***
	.dword 	$9a140064
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 0.012871 ***
	.dword 	$d2e0e304
	.byte 	$7a,$0
	.byte 	1     ; *** Load Float -0.00050105859375 ***
	.dword 	$83597918
	.byte 	$76,$80
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float 0.01337205859375 ***
	.dword 	$db167a95
	.byte 	$7a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -3.0 ***
	.dword 	$c0000000
	.byte 	$82,$80
	.byte 	1     ; *** Load Float -8.0 ***
	.dword 	$80000000
	.byte 	$84,$80
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 24.0 ***
	.dword 	$c0000000
	.byte 	$85,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 4.193573 ***
	.dword 	$8631c001
	.byte 	$83,$0
	.byte 	1     ; *** Load Float 649.73 ***
	.dword 	$a26eb851
	.byte 	$8a,$0
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float 653.923573 ***
	.dword 	$a37b1bd1
	.byte 	$8a,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -10.0 ***
	.dword 	$a0000000
	.byte 	$84,$80
	.byte 	1     ; *** Load Float -120938.95475199999 ***
	.dword 	$ec357a35
	.byte 	$91,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -120948.95475199999 ***
	.dword 	$ec3a7a35
	.byte 	$91,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 2.452675 ***
	.dword 	$9cf8a090
	.byte 	$82,$0
	.byte 	1     ; *** Load Float 2.452675 ***
	.dword 	$9cf8a090
	.byte 	$82,$0
	.byte 	$2f   ; *** Command / ***
	.byte 	1     ; *** Load Float 1.0 ***
	.dword 	$80000000
	.byte 	$81,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	1     ; *** Load Float 0.0 ***
	.dword 	$0
	.byte 	$80,$40
	.byte 	$2d   ; *** Command - ***
	.byte 	1     ; *** Load Float -6.0 ***
	.dword 	$c0000000
	.byte 	$83,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float -1.222980790771544e-11 ***
	.dword 	$d7262888
	.byte 	$5c,$80
	.byte 	1     ; *** Load Float -33.68 ***
	.dword 	$86b851eb
	.byte 	$86,$80
	.byte 	$2b   ; *** Command + ***
	.byte 	1     ; *** Load Float -33.68000000001223 ***
	.dword 	$86b851eb
	.byte 	$86,$80
	.byte 	$3d   ; *** Command = ***
	.byte 	1     ; *** Load Float 247.65 ***
	.dword 	$f7a66666
	.byte 	$88,$0
	.byte 	1     ; *** Load Float 5.312609 ***
	.dword 	$aa00e496
	.byte 	$83,$0
	.byte 	$2a   ; *** Command * ***
	.byte 	1     ; *** Load Float 1315.66761885 ***
	.dword 	$a4755d22
	.byte 	$8b,$0
	.byte 	$3d   ; *** Command = ***
	.byte 	1	; *** Load Integer 99999 ***
	.dword 	$1869f
	.byte 	0,$01
