SOURCES = framework/main.cpp framework/gfx.cpp framework/debugger.cpp sys_processor.cpp sys_debug_65816.cpp
APPNAME = m65816

CC = g++

all: $(APPNAME)

clean:
	rm -f $(APPNAME) *.o

.PHONY: all clean

SDL_CFLAGS := $(shell sdl2-config --cflags)
SDL_LDFLAGS := $(shell sdl2-config --libs)

CFLAGS := $(SDL_CFLAGS) -O2 -DLINUX -DINCLUDE_DEBUGGING_SUPPORT -I. -I./framework -I/usr/include/SDL2
LDFLAGS := $(SDL_LDFLAGS)

$(APPNAME): $(SOURCES)
	$(CC) $(SOURCES) $(CFLAGS) $(LDFLAGS) -o $@


